dist: trusty
language: rust
sudo: true
addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable

env:
  global:
    - RUST_BACKTRACE=full
    - secure: "Pd/1aneEheqb/Wh43n70bSoiWQqcPHJTM5UkTwdvur1DNgab7G+qRRU6P27/9wPo9fkvc7+NfN6SEerX9sJu1pSVou/3b1l9cAqcgNWYln5dSOSmOU1x7LDOoVZxJrHBHxdQTMWW3LDsKHNrn/lRLVOkHba7QLf4AxAvC+oil8F02jnAMh8kaU5cPMrQ7Y+nF+qk1SXC5Sat1WnW5IamWN6pkh+YKQ8potA5C4Or3mN905hyqkKz1xyDq7pmpVjvM3eoMAWHQ6v94l5bqoUMfc9LBsPukYPpBbcbR9skuRJYehvw110LzPc1QQhdIrrWqXGKckeEPu+A87sRbVQor6lwKHVaOfmQOnbzUYOTqxPMMVNCvlAsy6DbfnLb7oUIwtS4cZipjmPxybAo5EsBip7ksg+st9jnEW9vW376TlNgu/2kgKGBWOJC05lC+o/YPC7ISa99Ls/+ctZWQps16Zal0nemsmmAytpvBGYwB0zooD0ow4M5I7k26qiZxorXnGcx7ZVkHOiOT4jGc09YMrJgp+0/wZ+5uci6BvW1e/jgz7scIMLGYIkUr0la7QUL2hsvABqFPHf4lHMJqhn6og4CqbRDQLSm6cLjL9pjKucQG4xcBC2Vmvo2br24Cfom6FoX64j5brp7/m02y7/wWptH+/hcIXsztlmLsS/S79Q="
    - secure: "rd1UiLdzPPMuH/CwQPkYBQSv/CvR2mXkDGANkvOpaGC4Ch0NQoaG+/LWylN/8GCEaWjkBkHvTqNvxcGqjt+MCbHmVoUPZ0T30HBxaLWE725r57bKi+yk6CT6g7YCqlMXMabaCMo07AjDKnIt0LrbBmdU7PFuYCZTkIu0Sl/DN/c+ZG1P5+n/m3J3L9MxVabTmfvs8xsxIBOjlPGxmOX7C7fgeDSVRcSjwvE7lZBZF5hVupXrsAgnU/Ts0K2i6EaMkC5Zj4A7KUNtK2sV9ucssdceemD+rG4TSdnc4wZbkxi/eyYdKVvY1WPo8vp0brC89ftmEMzGgt4Gcat1pNz5aNL3wXf6kPEmIQbWbYud2tEXti0X6hZIwiA0RO4o8i2dSH62M/SsOuyxGYzN+QEbeVOnLVljfFW59J3v5VcJCm5Ce9zswCJ9xRwlbG+D/UleCgn7Weq66Ke4VUlPoD5Xi9CWoV8gjhh0hZd9P/UeQ1wdUCt9lZNrUSPUMEBT2h2X+sru0zQ/+QoRgcHqbxp1ZVTTCWXBIOZA4Q5sTdh2OPtkzVv/yCEVoWqySi8zxEE9GommMeFUlQK8ZCa/kqA3TW57vYaBQPaCVxYCPJDSpcwkHeKwGQizT4MYjRaiSs9L0koeKh19jYPooa8N3wTo6p/6sZumPIubHJTlLkt1vdk="
    - secure: "o2T1i38r32YQW9W38xVFxp/0nZdkvkgb/LY8/co/a/RtXcKw6yY2cRBBYwaTIuUG8pVx/ilITBLE0iOHfwI9wKqOPD3/iYSQyY4liVyP/hlrikxewjMJQuxQ9Ul55d4Ik+XqGpCE/+i30Ct/TbTqp7ltKl7adShfMaryzZJ3HvuTmg6wiKDQDmlRRRqGJPPYs2qqGSQ2s7tAlESU413cLiCNFra96WqQYrVWgt7zvpf1uf+8EHq9SGxt9zvY9UKiZwqzglMvP4HO8T0km20B3Qjo6zW4e99YS7JmkVl04CA62kd8OyAn4x/fNSRug7+uyqW3ypVwo1/cP8/pnQUnYE+CvE/JuVUPMU5/GNTYCQogN3jUh54b67fxm03tTGxB1IcF23Kt/bWtFePsUfwdM2Dyc7mZ28zWgroIXGe9FGpn0sZEw/PzQALF5I9dRuk0AnnQnvXN6U77zaDd/IoO6fjrF02FTnIRoTAxEojdxVDTedKORw4K3WAXy10IAmo522/tFQS809Edyg2m/KxPyvjuZqHW9vJnAAquVlYuwQc65pCU87B1J57FKkZP2+/X2h9C53BrEAH1ELRuubetu+5eW+Vr/3jowlzLpmC84dDb3RZCPICDBGNYv+v5ilewSQwSVstshcEJYOPon0KVKuJzBvxGbJSbXfoJEzyu+8U="
    - secure: "p4kQ4NcjRQaM32Mond+mkEKNDV4j6K68XYofvhOhH+iWsicuNqLWYIuaxjEGLVdDrUtk9qaNGog0ys9lnkEyFa/9WCdUEN+g2cSBR4NowDGIg4aBvobPW66wlZM6ZJptst0t/FNtbjXt/agDvSsB3bs1gYnuLA7QjvhwIXBLeH2uVhfYMaPlZxXkeHNHAIymCKysFc2q0AVQOXzPn4KrlAYnN1aeKooZvWZdAgw6SQUF5EBbTM8wiP3emJSCERdmwvh1H5rTxVN5DMBB1PZZ8OMAQA4c7zLAFJHcIAfm/FzQiOSn4N7n19mcDT400sNv+g38Smf4tbhx2EPB+G9Ao/rZpc1Qx4+xqnWLyjJN8VyrWYv/eE2ARdQ1Q9LejAIOfsTdSmpTyorzXPl9cxKj1oolqChHhtIP36OT8pynxc3UalL6MGNoLUaoBreOqRrw9fzbssSbiuAlr8s6z4eatKmz7QmxpTTVjj3kWD7fbiGnt89LXcEgoW2PEbwIO3BHHV38WiMO9g/l+cAmrOcACEJSS6x9v5E4VWXwsI1/JgrPGFqTSGpx7SuYzuqis9zFzondJ1Hzrgeyy4wcm6b2f99teplVyev2XgdP1dKorveEUSP69+TIUGrCIGmJ2sLw/Rpy6aRl70ryBqUTZchSJlzxU21okp5sLH1sdDDG3Yo="
    - secure: "aMdRt1SQlKqozFQDjm9hZxNZW4w48nIIZ75erJ2fkS32oDmmBcMjwt+lt8IeZ7IT45r1HYYjXyeVVVEFbswbG85WNBWRj9lVVH4P6k8DPRbk+ywZU39hBwfRE9crZJ+dxk+0V6sVULGts88wWTFYFt/FS07pfLiV4mrQJPpT94/Nho+8Yjk4sNYO13wwESEtLy3Maqp12qDPUyMA7kMEdhurUMJIClcrYaShyH0Wg1fHyMYnuaS4ubXFo5tvGqg3FSAIoLJz4eIzu+g6wzWjdFkRrPAl/whZt/c+JGPwFEFkVRmMTWTqG/TQGPKMbvtcCY0baoX6cVMNYxH7ckboeMk6nvoEapCq/nydmMybP406daQ4mHFcLc79MXVZylPFRz2Y+n8A8+nJh4BI6d5oINx0cyu+nJjx8SxeWyPRMDU++X3vkSOAUcVnRojrOGq+WUz1NzCMI1KH5ta3pXxHIjgQZES1PVi+IEcDEXK/3CPy+wW6aEWBIMgnFfzVxahzjoevZwxHUqKwLOimd+3zwX/8pnhqxZFoM/TyjeHQZJqMF9Tkx8Yg3GtzMVKY1sjTvpxGILy0yFsuDuo+QfM61CHyKyAty3KF/012g9zhBcxLvjVIS19BtrRfjjG6RQ1U8aS9tzuBSO2XcYhw1H3sHu2ep0bAUdbPbQ2VKc4CxTk="
    - secure: "bBt9tYr/PLZYRY5MxuSTHGN0Ivf63bEzcL0N6VXsjIw5ykB+5hhqEtgd2HIr80g24hs9etLGFmD1EDW/a/0WESkzXXqC8R6wisx+fRaIuO+5+uW51b3osvn8RTgKTl03zilSym+5dZnyNDpJlnUugj6U+r/gkVgNXMFETZrnUfZjkMz4X02LSglhUhECrxRnxvvVr6WvSF5T2mh0zEdiGskggsM99dUtyMv/fePACzoCyZZ/wIywZcnHtLIqA2c8vnhFI7gtEQcD9gd5uINSxFWljIYOS9CHDC4Jxi7hOxXq4gQcFZbYMlNZOsyuVsi+K1+WPju71XQ5rHBdBG7tR8y79lxdO3NP9ZTkRVfO3c5SA578Vi6OOTCs5hTC7xF9SvmcU828DNEv19mR3LJNnHVBaP42mpPs+fZE7H2tXGpV+wVaERknvmNWgPBv/BcPMzThtBlpJUvbalDb2Vg9egGEsHuiNHw9cJNNqGxeldtvvz9av42wc3kNiA7ghHDCK27T1f6Dy6XRTriEn9eS/UUjeUvyIp3EzkMFg/KaYIF6EzCWNYvFI3qUNtz4faFiNuAV9MG6E7JWzQMZKvMaVnjjdllT5YGXb9WsRmM0Pr17OsbZSG2494dRd2WKqZRlcIA4UXAdRba8V3dGzsBCgTEzHHDNtTuSMY1YmR4DYnE="

matrix:
  include:
    - os: linux
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-unknown-linux-gnu
    - os: osx
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-apple-darwin
    - os: windows
      env: |
        TARGET=snowchains.exe
        RUSTUP_HOST=x86_64-pc-windows-msvc

install:
  - rustup self update
  - rustup set default-host $RUSTUP_HOST
  - rustup update $TRAVIS_RUST_VERSION
  - rustup component add clippy rustfmt
  - rustc -vV
  - cargo -vV
  - cargo clippy -V
  - rustfmt -V
  - |
    if [ "${RUSTUP_HOST}" = x86_64-unknown-linux-gnu -a "${TRAVIS_BRANCH}" = master -a "${TRAVIS_PULL_REQUEST}" = false ]; then
      rustup install nightly &&
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo +nightly install cargo-tarpaulin &&
      rustc +nightly -vV &&
      cargo +nightly -vV &&
      cargo +nightly tarpaulin -V
    fi

script:
  - cargo fmt -- --check
  - rustfmt --check ./proc_macros/src/lib.rs
  - sh -c 'cd ./proc_macros && cargo clippy -- -D warnings'
  - cargo clippy --all-targets -- -D warnings
  - |
    if [ -f ~/.cargo/bin/cargo-tarpaulin ]; then
      cargo tarpaulin --all --ignored --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    elif [ "${TRAVIS_SECURE_ENV_VARS}" = true ]; then
      cargo test --all
    else
      cargo test --lib
    fi

before_deploy:
  - tar --version
  - tar --help
  - cargo build --release
  - mv ./target/release/$TARGET ./
  - cd $TRAVIS_BUILD_DIR/..
  - PROJECT="${TRAVIS_REPO_SLUG##*/}"
  - ZIP="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.zip"
  - TAR="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.tar.gz"
  - FILES="$PROJECT/$TARGET $PROJECT/LICENSE $PROJECT/README.md"
  - |
    if [ "${TRAVIS_OS_NAME}" = windows ]; then
      7z a $ZIP $FILES &&
      7z l $ZIP &&
      mv $ZIP $TRAVIS_BUILD_DIR/
    else
      tar czvf $TAR $FILES &&
      mv $TAR $TRAVIS_BUILD_DIR/
    fi
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: "XAis0lOhyyMU7IjlDVTMcsOolG7ZYwBhKuTxX5pK82dgUmLijxgMVF3zcRifoWUuL9fXiDh6jDUkDPOFyv0SpUauMk5fVqvr7zmRKic1srRBsRFPW9UvOqDx5kg+MeO7NQJPFARyDzwNyl+Sb7WONslFfiysLW4YBruFgQCgaHay0G9icdRq9czJzKqAticLec7421w9bt9Rj3XmuoLck72AWbaT94H/hH0DTNHcZ4bIFfoZVW5D6swSGrUrNxrKQLbd40aJ8tNHZS/PnEnmsu0iS9NXbIwQys5w420MgP2mz3lg4c/FXf//2FjpgmKxFKEEbRnTw+BSjDWKxw2hJv1ojDNxsWymxfVwRdGWj2uXcRz9Lu1d49G1xxjnzak9Y+KYOKkAOeZ7RV0NUGWsUzT14trb7Ug4QEfp9tY1dKbZ4Nuos4+rreBjSyjUF70eXLncwWzNmuPnsmNcPa8jygQAqwAw01XMZu1grSRLmlOUW7eazpwp4WHgd66Hio0Y8mjQwZD+0pbedt1LND939vT/FrlOu6EYbRvCQpJSNBbfVB5ThZzaTrxZhHEq/IgHklSk3OELO0lOTox/jeZ2AKcoV2xZ7rscAUnbb4fJ9cR5IsXHIi2SfLKgGKqt5rlLU0f96C8uG3XUAWz1yi2Gr9afSGDbNYcD1GXPy2IjBH8="
  file: "*.{tar.gz,zip}"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: always

branches:
  only:
    - master
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
