dist: trusty
language: rust
sudo: false

rust:
  - stable

env:
  global:
    - TARGET=snowchains
    - RUST_BACKTRACE=full
    - secure: "c9r1uyQKOxKc9w+JL5aPmjLwmuwM4Btc/NE9NtPmLycOAcFkTkRs4mCDHfnrgfbfiVH5WDzZJp79cnyEXs9ze9fWB12zLUOCnGdh0sxvLRvnkbxHtu2I9Ip4GgOKnyLY8vGeZfbL1VDWj0AlIac/0601bmodMDD+czDqj7dacdCKhAVmeERPO+8EiRPjx3SXqUerv/McKS/ZhP8xS1YHFCJb/EtKIWIHruh4PX6J7/EtR6PZLzmIQbKyZGUxSVpYSLzIinOYSz3PBhI1EubLyemBDOwhcrm+qtg6jfEFuVeZu68HrD/VJmItGVDXoCl1jkRn2vTkDko+45o47JHKmlH4Mfcc0HgERydTmB3MqIzd+gZuILMDYpLqGGVwEuOK/AfSh2XB82K7019M2Xz/l6VipCSqjNrwYRL3qwo9aRRGPnp8W4TunW/rbP0sOuaFhU+gSMGa9qD1C9PdVhRiNzfR6Cjki6A8fbMLSTCQp5Bg0Faq8rNftw90znv8lEbupl2HkdM1gsndfnIb2htVULBsvE1MsoewNnYwsUDchpH5TYCfw/w7vp/GeNMTsGrOQZ5c693K/jxnfZpBUxuHas9ZSlXNo+BwZDErh28+VVfqajEhdC6gH4e8D0FAZv0Ojgl6JpRHQehdLqxm83QDGb7/1Cdw7dmghhrBRtDcFMY="
    - secure: "wRWqwtWGj89S/54Zv3s19v6HHe2B+ljfsa6HLUFiPjCwMbSZAdQqj9vhA2c6zcqhb8rCDoIxQXBPefum5jd9AF26tHUa8GzHVNPPF4E5kU6sBt0KYGmufaNUcEoPVFrcV/v++h3BxKXKr8ZSJbdCQwMzJqPvLWIEUCihrGnYvZeWHHPpzKU13UmFu8XE5uvaWtxueb8fLa1qQ4odPmzE90dLs7s8j67BuCMTx//OntADQllvMXxAik9tBQuzQInCC89H3FrBvDtuHzflZh6TZBDwIjsFez5iOhXS/4Ff/5eDTpMyxj9oDqIstc+RjrK+FzZYT+hqgeQR03wmXLFb7zfLAGZMeWlkui6+OEpJRyCSe4iSdq3S/u36vyn7WvvX2+Rso98bYACVZtdNV9zorQ8+DfYG0vAKYzYSlWkOZCvl4kJCoRO+xvqskZl2pBY3w8WbehExiPemNX6yxkhGBNBCB8OQ9sP5UtfvDkgAL+7U5Z9FwV0pdKn0lt6p4odcHjxFggJeHf39O24Ko8i72FmcGtcJjH8ZMJ9AWbI7MBExnNYu/0p6Ru8o/VBgieAUhvA1fNW5bAS/ljSB4kRds70Gxn24nv7cpfVf5cRgS6SjL2gXfN2oKqxHUI/hfKFsldkUOeAaLNWyjF4vDm/xpaqueKoOrMom9aIMtPSLuzA="
    - secure: "SovQbV82y0fC06fb1Ryr1Y981vNhrXl0OBsDhEkJTUQPiYaXRf0IWN+ntRQI59IPZQDHS77LPTq/Piu3wrNV1ia7bLlIyoFfD77rmQcrScMpu3uFG5QhET1owYrhnyquWd9iVI75GXfkqx7k83ZnK+zt5t/GjvL35mHKLvtgCcg5VGmblUoOykfqXwoKA3E/A8ZvRGc6UlrXdLEtckFsBpDg1jRl2qXt7eC7QEPgstKWx8jwAr0Bv+FNT/QHxdEVbNT9NnLdJeYmfoNm2BmNikUubW4hSx3fGpSU2USaq8UlFkLy0O9Ia0FF3jI4l5uC1mOTybO4DNEbELzBN0LXyD5Dr7PMxVox2iemLzY+Vsrfpqu+RlWVh/S9rFDY9CTzJsQFKFNvgQMpqDVMSah+KPgGqhvNxI0cGfG9Y8zIU+YzPWxy5QLxW8bQNNrlVFSx2HCe5CffHowbUpwcmgxV4mnHe2Tnz/vU73xe0Qyu4XKTcw4D+6VmYxgTbIb0ajSYlOneum5CxQ1FpE8SYSVLCrExEpacGJ9ollhPJUn8mli5zQ6tS6rHWXfvg/8p5Zqq7TnFv0BjjIH7OGjeKORm76214WpxsflVzPcnaZwho9xcfEQ8B/1Rm2aZNULufWxN5w/+8Sj7muzXSOKpEp+DgxSs65IROgUr3aCR+F+6Mtc="
    - secure: "GjrloX0ML1cZgmWER6mNNH8h80rWWuFrPhQgK4u9dhwB0NTb4Tt7SuyYicVIZ/atcMkJ84XC8qfqfMEtq+Ui2gem5t5eAKGoNMk9u/Pe7yHK9kXqbitNaN15jSJIKwe21EcmiLPRdRffcKmlnj3qVMD7JsIoSkHNm8MZR+dUz98USyESAXnNXjnvNHgc7FqXiseCbs7dbEBqJurF8/ExRwxykrGnQUVhrWS8CNGTTbdjWFXd3nY6WVx+j7DHLX+wtCfQzaUgjt51kiprTwJOLeNs6N8iMvx/7JBuBZBclBw1bgkB4kOcsumPyPxqR+Ywhgg+rZC89MPL7gx1lRkpE9TAfiU2E7CYjSHq2eTqtrPFlUXdDg5ecPkDDk11vLXElSkgoSWP0ZUwBNRGWxEJr8FlKZhV+VKvwvyIzdIWk23Bsxq9Xxiz3DTQu1UAec7IacZ96hZEykJYPh3DTT3dhHF5+CRMZoTwgLJiH+qaSvJfpWFuY0W7ep6QNtFjCxt8uaUUz+5fK3ASBAE/8s4jW+BRgJgzx/AskuiRqdJDDWnrXZ9v1vJJAbKpXIZsBtZLl147s9TREJ313OH8zCq10356WKjNpz/epd8QCbxZgEQbUuAQGx7pMVq09blfY2z6YGgGA6t9yKuo80Tf2YMOuyDOeOcXdd94unIlyNOhbAA="
    - secure: "CpWrlsXUUdn+oZ6wgffbc3Z+gFCmgRiK1NG9bO2KrNh3R1EEXKdeFhIdgOEGSNR4SHKVybFDAnyCo3jnZr0DljBd9nyWXH3jzNWdgLkx351Na/3ekZE3m1sevnESWJXXudMMgTmJA1HFRJqjQg8kd8gnfnswd64M8w/MAjgerTzJLF08JYVIkTwNFrL/Tdr4uPNgRnnNZZfB6GSI56RDYpmxNH81gjG0BDA050FOngwU0+p4dPcTF4VOrqRZL4fgLS+gENnOQpP9gK9YDzM0Itjqank6mlUsyneAArFAozrgEwqQb7UQX10OLcBBkc6SbnvFoiFOA2QcZHzjeVHaZHkKVTQJid2r0z2vbhy5FY95CUCtXvTOevFXUT1gEYQvmX9rLpTts/I5oZCQxhraEujiRIvLnL8JaYMU07RgtdmTe9V/F8NkPf1xtFQMTQIVsOOJxyOXgfwJba6eevBLftSPD9T0pR/aRzk74tjYQv3GlHUKaGrOYZ2PPU4Ps9B7y1l5niuX/PaGaYRG5GN/hUYUeUTOq9ioA2H1RggtZ21XD4ZtBK/QNAdSTWIutgol0yyoqPObNNw+xmWU03J/xuiFCItK1TXpTnQhLpmbtF5hQoBtwcCDJL23bT/DGiAg5DR3y4Of1VfQsoeNtmqWgCNmtrICCocgcTYdxgO4hAQ="

matrix:
  include:
    - os: linux
      env: RUSTUP_HOST=x86_64-unknown-linux-gnu
    - os: osx
      env: RUSTUP_HOST=x86_64-apple-darwin

install:
  - rustup self update
  - rustup set default-host $RUSTUP_HOST
  - rustup update $TRAVIS_RUST_VERSION
  - rustc -Vv

script:
  - test "${TRAVIS_SECURE_ENV_VARS}" = true && TEST_TARGET=all || TEST_TARGET=lib
  - cargo test --$TEST_TARGET
  - cargo test --$TEST_TARGET -- --ignored --skip it_submits

before_deploy:
  - tar --version
  - tar --help
  - cargo build --release
  - mv ./target/release/$TARGET ./
  - cd $TRAVIS_BUILD_DIR/../
  - PROJECT="${TRAVIS_REPO_SLUG##*/}"
  - TAR=$TARGET-$TRAVIS_TAG-$RUSTUP_HOST.tar.gz
  - tar czvf $TAR $PROJECT/$TARGET $PROJECT/LICENSE $PROJECT/README.md
  - mv $TAR $TRAVIS_BUILD_DIR/
  - cd $TRAVIS_BUILD_DIR

deploy:
  api_key:
    secure: "f/bN0XER6uts/ncTIROxd7TQJ0/+5aID5T/puK6VNr1PPb/6RsckShYc7F3+Arm052E0AnnDnPuHttNCp4rDemS4tjSWgigc8AxKqzQDFbnVNSqKXND+aRHyGMbHMNRDa36/jl74/evQWw4dLKgoYFJ6PZq8qkEuT8sbyK4mXHn7izom3O3LYuH16dco1RCf/1OxiAXn2WjnAhCEZrEIJl1K53dXtXCVEreh6WP6TUp+q6gZqKiHU5IFwlDT0D1Y8FwiOgXGeHcHIzUEwjSlN9fj6NEiG5JkZ3YL364gkswSanUhq1zE9eazQc3Gpt9oz4+xClpB+rq3aS8bk07SySm71GNWNtEyPoTUaE9J6h3KlFLacbaCH4lWDiCt6/x/Jo3jxC8ypHyy4TtpQMas+cKM7OrUKo6BiqhoGoGj362ZJIq63jxJ40lHA25DrUUhzk+ab5me3biQiy6ujloPduIdFtII9R+sfOUXqADVw23Q/Dl2/ZmiEBs4vYz+kw1gvG/HSa93cp9r4VV4zZOMsgbonWTIhUOIniteJZYa0aAMiK7h5QvNKRhLX/vWJMQoWYbiFi7pnWw5yyvv71ycvHM3eGfpG4n4VZEbkkFLZmuG1t8dFYvEkkEfBUM0EFHqbBvoOEcs6D5kq1I2AS30XkbofiE2xmL/staHOHhYbYE="
  file: '*.tar.gz'
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
  provider: releases

notifications:
  email:
    on_success: always

if: type = pull_request OR tag =~ ^v\d+\.\d+\.\d+.*$ # Beta feature
