dist: trusty
language: rust
sudo: true

rust:
  - stable

env:
  global:
    - TARGET=snowchains
    - RUST_BACKTRACE=full
    - secure: "A5yvisGqB44Y32RQf0PjohykmnMqP+fJoG+aQGlsuLiiqhPpIdiojHMOrqaPJ+vI7ckTxF4KiCut8ZNCrSyyLl5oyuzWuJggv2P/+R2Hvo9iI17pXk+4iTfFg4ZCtEiK1lbTmQP/W5oBXVh077VIYGSkCvJTwISrwEyUjqH/JOJTEZdBXYa8qXYvFLUm0bNvi9UhxJcTHTbT9ieaL8Zkil/A9I2KpgIc5uv5vU0QIwPH2gh7m3NgJWV5msQIpAaSt/W1H+kk50UBbzuYw4uJLuzSLMF2UTNrORhQXqnVZuCuLfO4BgM/YrO9tGTg02wRAGxlbqr6IdWd9AaOvPXVIuezGIeixID+GYld6t4G8mngIG9gxbvxxzjZOjCZCvGFapK+Z8vLm05KEy8SIilnj1nF3C/V/ZJOtBAqR1vOhx6lowW62tbCNHTnqBPpprzrbV+ok+w6eFr8bM1E1m+fxFbOrCru3nV6yDYIhPwQDlCLbnKERu/VouIQlrNAjISgM8aVhZW0fzY9ASl+rKFYTJVV47t4sxtdqSTyqe3E4ALX7iKmj7cwFn+DualSkGob1T1jC/ROmYD4VfEXjjqnf+Kt3AOOaydkguoo3imvW9zP+/jGzvVlcJXGJxpqZI3XWJrxD7qWr8tPzqIxvdlsbSu9YIxpydxKhAAWTCU2pZI="
    - secure: "aasanQPpJeFF8sdD7boa8mIh9howkSJ/AcYzSQeNYue4Frb2mWQFMQFWFGcNzitgyZedunt5BaO21EAt/YX1ZB8SCpOExG12QqngEb3XoKg0ws4G3U5fcTVffIE+uX+aCX/Y7zgvfTQtsqB20uHO5vzt7Uca3JWjGWpzYCeRpjviJC/ZdrlIAdu665tFr4yKpvHOHF8N+ICqZ05I6egKGcKP2vhzoZNWvO/K1E+js08fTfUOyuQHWqFB2evtZPnkOJdGwDC7OeFV17wUy2eAkUrsAzHcCDho5XndQf4hBe+bTqSBXXDj4aSwkS+EFrgG06DWqF6yEgKwzVNxGToE+AK71Ig/eLM/s6qR+kWkncVEGzTUyLJBHD19NB3fhUlZdvIC0daU7ex7mO0dXwPFQgnpV+HiJAVyM4rbLcSvQ5o7ha3O92G0UCHc9VXxAWmPZrbtABF9iEeyT3BnXdOK3BH3eX8itFiaC3Ej0SA8WIGgU8k2Y6v+frDGyCeCD6DEEcpZl/4GWS0hUEUC4Zuvi6Ape5mKqwITDOvRQP4+i9dQrvuM7euobKKXOOusLoeZxYAUjf6ZGfGU7zKSttdRb4NNPyfEdH/9v9IJ+t1ZlUT9DVf/xnxw69rj4mLm+Rry0XP3u4QvVGasHecWHfX1HpjiPAcdY7+KlB437pE9QtI="
    - secure: "K+qMo8RKTYmhGR1GsKNUlTzf+Wh/WOEOaoEO+PBJ7TuoJfRSqkC03XKT4QtLixXF8UYahLB0RvH/b3gIkcUcwdLNVAfVe0OmLlyskqNPfbW6NG6mcslc6bYabPb0XD9ARrI9XhHR/EDIRQIzdIy04kVLgSI6ChDGwfqsZrZa4cHD8gAFJf5RLi4NO0pO5D0g15ZpVtvkJvBA0d8+87iYCI3EOGFy7LSP0B4p+gcmMujmBhcWJID77EOEr5sJZExlDgHNujC1KVwuzt2uQdrQKqvSXYZKlF43nwLkXSbGVQNydYUCzWGAgqrH6G0Tk4rjXNOFUurIB7FSiV0GzcOFoRRWyCUqtIXH5fPhw7/DSe5tyHE4HN93SbENhTKqKtNITj6LOzcE+T3X0CDHgYJFJ8d7giDS/JhLZDucURkxrvKLBeyOp5+1Y6YmYfD8Fgl7C1Wh3Elnwo4jcJu2gj1ReHhtAB4HEkPhZkRV6nf2O0Rf5I0w4exkPeW0z5RhhvKcqKXkh1VB4tUSuKf+KnjygXDDi/k4qeHbjRJKtGkmCdej5JS5ZY8bkEUzVq13jqfWA8wRlZwa3Zn+ybPvJIndaIfCIkkRJ+fsJFNiLVgaKzIkAZJAki++6AwNB5bF1U9YZuF334qbfLuT2BXIBN2IfcC7nAweGDGmtAe2mHM9tCg="
    - secure: "ZJcbftrLWXVFp6E8aIAHOKrU0hCGpoEiaQB0roqJeOeNG+mfuT5TtITqZKBf7r4j1YdX0dowmbGSKb+jU7Xh5surwywh11OqG34lo+7fr4zGttoQDKB/s0o18ipoqfhT/E8kDmuaHHtwezdfVzdr6rE2wTyXBWvbyiFYjh+hgHerAf8itxaa4uxbdWY5kBfPq6sA7+MXzVrbi/mkaKLFNowgEGQUMDzkht0lSqpFIWv/ivNne21oDDWjQcGJy/VZvypaKaSltPzNmygrHoYtz8nEzQo6tuGRbK6ThY2WYKh2STNG2acxlMMYveiq4SHIcm4j8DMiynFUeG9J822kelPtGn0YcZwvQdVYmBPSRVD67akVNpH9V4019Q32yhmziewtOTGLkWYzSkOUheyTacp+AGuIXBO/LN1kltWnFTjGqP2AhpVWrI6apoS4XOuev4mxupcoj5KPse9TGImukkB9agkvckeOzD1meQeFTTPXarrBN3kgfOgX79+UBknAR/9eSJFVBRTQSUX1UcXH3o3wkRUoAIVl6u6z5AHK0qiQ5gtYpc1LyHKDlQf2Z7+bsVr028EPeYPZivY3XBYUwFtpgHHKEsjWiulod1iTsscHVkt7hWR9mGuy+pD2DW93t2Q2UI7NlT+BQ1V+0V72GmaALyUm54CxUIrWs4wGK2g="
    - secure: "L2BCSnKOXR9bwxacCKk5R1eI4NjFH7t9v/nhWlkb/sKs8dHWweH2LGC8q/oui0BURdT578Y/yAe2dmTx9rpuyb6zR/y3NlPwaV+nbG2N+LaE71zrx0cZkICGmywRKSlnUGBBt8H8x9MvXs4jTstHMIXuV3gjZ5hcB1csu3zeyAO7zdQRi2hJNuggMOl7r14xFY38kHmbffzStXk0/blcIrlHrWU3ST+f7KUQfHmn1YdlPs+B+tdNvk15WarL1nzqJG/LEDk0t8eeCFEdDgemAeAL6qMzcNFL2pnUIwxoAGGJ3FaW06DUy0nwsGulmVkyeu/ksnVl5L9ljyPx8W8KaGsg5+UzjATYDNR+5xCbANlT8lU/+rmw0eqVZQ9KKpF+57f/usWN220oSAPsktjDoPZRyYj/lqWGtxzrNO0Z0Sk+Emasmcx+dz23M6rZyK6RDWHboYOwFJ352ZYOlnTnYXbIjFjURBzMRpDg/kSSFgMHLNx3wQkRkRClsGiIk8KEZVtaiduhcNxKF1jxF9nDiw/Wg5ndBoUC2NRqGNYb0cbWvHv8rHJ/yp3jpIHx3aJTmVnZgN3Nt2nlfj3SWepmuh/99gQOStoMAHSwvjbeqFeaFltGV9Urgb55WTnrsyvVh8OHPTw8hXoG6NHC8tiXNq4kh9g+C7257cCgEfaM6Vg="

matrix:
  include:
    - os: linux
      env: RUSTUP_HOST=x86_64-unknown-linux-gnu
    - os: osx
      env: RUSTUP_HOST=x86_64-apple-darwin

install:
  - rustup self update
  - rustup set default-host $RUSTUP_HOST
  - rustup update $TRAVIS_RUST_VERSION
  - rustup component add clippy-preview rustfmt-preview
  - rustc -vV
  - cargo -vV
  - cargo clippy -V
  - rustfmt -V
  - |
    if [ "${RUSTUP_HOST}" = x86_64-unknown-linux-gnu -a "${TRAVIS_BRANCH}" = master -a "${TRAVIS_PULL_REQUEST}" = false ]; then
      sudo apt-get install -y cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev &&
      cargo install cargo-kcov &&
      cargo kcov --print-install-kcov-sh | sh &&
      kcov --version &&
      cargo kcov -V
    fi

script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets -- -D warnings
  - |
    if [ -f ~/.cargo/bin/cargo-kcov ]; then
      rm -r ./target &&
      cargo kcov --coveralls -- --include-path=./src/,./tests/ &&
      cargo clean
    elif [ "${TRAVIS_SECURE_ENV_VARS}" = true ]; then
      cargo test --all
    else
      cargo test --lib
    fi

before_deploy:
  - tar --version
  - tar --help
  - cargo build --release
  - mv ./target/release/$TARGET ./
  - cd $TRAVIS_BUILD_DIR/../
  - PROJECT="${TRAVIS_REPO_SLUG##*/}"
  - TAR=$TARGET-$TRAVIS_TAG-$RUSTUP_HOST.tar.gz
  - tar czvf $TAR $PROJECT/$TARGET $PROJECT/LICENSE $PROJECT/README.md
  - mv $TAR $TRAVIS_BUILD_DIR/
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: "kGJlDoXsyODaXd4nXLfiAYNp9YbHbf0zSrZkLy3BYIK91jJeWWZGOk5YihINQuBMTu4qJflLwStvaJhKLcJTjfZXMCX08ND2D4kPEcIq9F1Fi4hpe+PuLIO6ox+L7X/veTELIG6iDhCr7en48+7YfziJRQnXkfws6VBiW2UAuPJ3BXeNq8c3rvFlJCcxQ1YUL6IIOXG9iAwb5ejzQXJ+CVVos7PDBHvnF3RP/2cweEevkEutWSFbJD+/9fZ+45tz1DdiqixqyB7ipakfIOLyNnZw9BPgsCisHHz3iYhxTirPkKMCaB8C7C5CZ304Y0KZjer7iAH4xkToUUJwbzRYhFOJw5Hi5xG3l8iHeDd1YC2f+bj+StLQsO6m16XMhwYhmvn2x5eQXf6Iz0D5qKAaS5dgZYQ0oON6kkfUULMAxSKua5KyrtTA9aepHjbnyirMdWq8deotfJ+eTwmsY9jfKnf5QWCPXyXWs9kjotgPPOOeL+fw3cP2MbVj2zP+auGynjrnSv7nyBbHEZuofX8e4VMzE/zvGQoJMuhchckEpdDd3RqQ762IViUU6cgTV15t3Q0JY1issvvNo2S36LRNpNbXJykGPodWK0XN56heYFQqwhXyl5xHY8mVkshKKGtRNLAwm9oBGS20nYt90VBotAWOfWO+GzKjOUvMC2CMUvQ="
  file: '*.tar.gz'
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: always

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
