language: rust

rust:
  - stable

env:
  global:
    - RUST_BACKTRACE=full
    - secure: "lH0uIumC+VdEZ7P9jaSWNn06OFhjj6gIZHQYQkBftfh5hDussnOSSEV1aWsZddpUXBkeioSKkv3tlA/UkOMI7SazMfwaWuxTy7fJZTBSaDkbE3Wyfi1wXCTEFi/XQ1KpYOxafYKF9DsPcWK1Dvdoz7H89jvuoXed1TrQUaZZa9IEOW0OwUK20+BsWe373JNUsCGXAvf+DMxvHSZ/8irc5hp/5tfaiL47Ds1iWvqFReFhZ8/bnz9F54oG/A9+uUp/FtbGweay7zI1bZPnNgnjAHsnTNaYkz49uEnz+45z07XYC3jWe21aRuuPLgpr8Y49ou0cdN4kgDHj1JBWTwle7f7eD4bB1LjbL7jIFqjxh4FWj6N5qt2NKguECfqPCXcqjTqCr/NKnK3tbggoEfnZSoCzFB79PYoEM9GCCx3XylBesURqsyFR8rWiUQeqv0SCWhga5t/n6FovTx+YVVDfnjpX6W2DXXr0VGiIx5o5WXj7qAYXHKpFod6YPKMdS9lptZ6SIsxBMAbXXG60eBBHFT9gZE36Si1SBkT5hhK1aDfFPGRZaXdtgawwMOjqcUvPao5f8PdgEC0rHxMDruoXfcUsSd2pyGksjV7wBO5Q0vtDw/Wbde1euyGemyxlmlZOKSNtChEVVDB0wtn0ZQYbHs1gPZ0jmFGC6PaFa6b2yRs="
    - secure: "rd1UiLdzPPMuH/CwQPkYBQSv/CvR2mXkDGANkvOpaGC4Ch0NQoaG+/LWylN/8GCEaWjkBkHvTqNvxcGqjt+MCbHmVoUPZ0T30HBxaLWE725r57bKi+yk6CT6g7YCqlMXMabaCMo07AjDKnIt0LrbBmdU7PFuYCZTkIu0Sl/DN/c+ZG1P5+n/m3J3L9MxVabTmfvs8xsxIBOjlPGxmOX7C7fgeDSVRcSjwvE7lZBZF5hVupXrsAgnU/Ts0K2i6EaMkC5Zj4A7KUNtK2sV9ucssdceemD+rG4TSdnc4wZbkxi/eyYdKVvY1WPo8vp0brC89ftmEMzGgt4Gcat1pNz5aNL3wXf6kPEmIQbWbYud2tEXti0X6hZIwiA0RO4o8i2dSH62M/SsOuyxGYzN+QEbeVOnLVljfFW59J3v5VcJCm5Ce9zswCJ9xRwlbG+D/UleCgn7Weq66Ke4VUlPoD5Xi9CWoV8gjhh0hZd9P/UeQ1wdUCt9lZNrUSPUMEBT2h2X+sru0zQ/+QoRgcHqbxp1ZVTTCWXBIOZA4Q5sTdh2OPtkzVv/yCEVoWqySi8zxEE9GommMeFUlQK8ZCa/kqA3TW57vYaBQPaCVxYCPJDSpcwkHeKwGQizT4MYjRaiSs9L0koeKh19jYPooa8N3wTo6p/6sZumPIubHJTlLkt1vdk="
    - secure: "bjXzTQmZ1+iRC9XABXR9/WZd5zisVKtjSheJQ+1HupmjNXnBXT/3Y57P9fCLdxtrIaK15+VkmkTHqdrhrTFFjZWuBfh5W2rs7ihQBAhtbO/1K5k3Y01siI6VtDlTRNJHIOHfqPnl7R28ogiwmyCuoV6EUSv76izoNZZihvdRLudSTMANKqSdU4Hcs2eWgQpA9r+C5wYViuljao7z2XCFyAHzqUkwNks61wDAqjY94LT+jSxPNKC5JW6mK6q9/jaXlH3s6ZEgN+KOttVgUJuI/TYHw7xpJmLvyBbCbm5ODSn+zxlhpyF4iziLrJB7kk0oFjRSSQwQJWtv53hmmfhjxOt6IA2wc/oBFA9zBcmMw2qhXPcvCMAGF2psAgrCACNO/GiOI0DbtI5pktDCgLVw2PoeCqnrtkc0BA0uZ2RjkWvgdhlDuEI2u3wo2QcN1iwbg1GeMYclW4gsIaaOFDgzQDaKKuI5RUMp9C8yViF02uamsSMg8C3qmmuyov3ZYO28QXwF6MUH7InNLK+IHkz9eszKfVty2EsqDukxaCZXy3Er4/KvWxA5v4b7NwrX2E1apFM9Fn2FF6TwFPpVWmmQGf17/1EDLd/ifzReyalgHUjOQevLtLTMXA2ytASOeXFNZmJM+sqktqpMh9yrMGTUsrCXKQcsqQQ7B7hyHO6aOh0="
    - secure: "Y4h8/zJm6/cuRiMXM9I7RMRlUtHVYgGDV8O7gIEDVmDj1imIFfy0lDlfFYCbeIO2rwDODs+fDcP+BV/OXwiW09UWHQGCDaOsm56WhbZRrX2FKIRfBvzPy38OuXtY5AvFZTvuLx2Qza4G8Uq2gpIXYUD4t9mjlcbAPtFv73sS9PRHpq4FlKnrzETtpP6NOSMWp4HGJ04kGkJ0Io99dT7yB8bysy+uWSXmNJqKA/XGf2SvPtD/q8KTUzJX4d56Fw/Uz2cSV+maLrsIF+xqVzaqfhMvbeOlxaBu7NDpfW6OwQQz1yejSd7eywlKwhOwBz2hzXsdvRFHSTq5pS1wCZMTkjpCLb1HOH4IuXDmmVy9OPvSVh+0yIiuiYQ95ezzabn5XvBbn6RLMWki0d0VWwA8y2MWjWR5ZG89vNpcma9EKGLozcJFoZt/nsJuCX0NaHRIhe2OqyRJGd/LBasJBoP0XCu42OqrJCbU/hbmkY537mWyKLn6WR+0jujpN71grKS1pZppiJb7RAXUfnKSx6rd3qzUdUV0/lhk0i9/oV5R9B5DfY/HHWyvziO0ZdM3ie4CqC2FbpfZcEpd3uJZkFoQoUfS/dwO9xe3V7Ynprh/9TJ5JnYbmpol2uwVDG9+N3kGlymhq9pazCn+AKxjs0Sq0eD2xnP14Dj1VFjKtWrDVZA="
    - secure: "e4nfNyRHPHalApditzfYrNc9D2mOp5slz0X87W/qnhl+hM9SOG3BuABn590tSfT2eMrMLN0uodZogXRxYnr/A4ZpBoVRur9IxN8XgkMuOH9ZJzfx5nGI9MMmN7ffKQDfrYr9Q+YuCkWBx81a414CQDASCBtJt+/oC2+pkhA9N7RRqm+yz2NGvgFIvTMhikSLIXKDkiXkEZNcN/FO1V4upOfvdI7EilUmB8uUTKUvqb+PuqRuvXEPoLWLvNJqhQljs0A2VR8yqAIURrIAjcZzp3JZ3aO+v7FzB1obHCZzU14GgDbn1uIMA11mj+guGOhuXbrFo5tw5B62gBo4IpsS8u71Cx8oH1rHcqQ0BE4fQxT3dnCRD7s31Nbj5LcokC2mt6XqChAi8cWRZA3raycA/OQlgM9QF0B/PAV6QPDZFzxkuqKu55T0BmcSqecwq1OWohdBYoqfALqr0QII53Su1UjVbtPxCj5SAVYzp3DyErCGWxs5Wh7VElBvYsk32/SYtIQZiTpmq7Xdogm86alqGOFdp+rVZUHBF5cGzVyIgiKn/2nQ7bvumb5+tWe3Cmr3Iolgd2UVOqs6gCpdzj1GSgs20Ia5DJ3zXBC5FXJPey0LunvPhS0rtXxKhMGGeXNZXjbnW1vE0VrgFlZMncyNS7/54X4QkTJyvPFNYZMs2pU="
    - secure: "F9k9kHT2zRpEn7bxregMJlJxyYUu/ntC6UPCiVa7YWYeBYiLxRX700DzPUGXjXDPbh2v2xFKSE8S+74dX53PX0A5Kuw83IhYO3MZ0fWMUxxXXaW2ASbXHutqphTmQav6p0gE0HqdKfhw+YpSYKE9LB6SkUPC8PlqkZ7bHYhO6FQBbhxSxcZpf2kZXysDDx6gMzIq7st9u6ZGRj6V/YcURH+DPnQhDPyYcYDmEvSujSYjGNUJ0mc6Z0Fc+Ybi8Z/gmD4k6xD+V9juNB+uC3raHIgNBEvaKwkDpx3fxZ6UMtdChdeLqjMulaCQPh4R78BRIG91DP4jbeWP3vheB1F0Fs6PM9+8k1xSqlbfajGt+V9ZEkO1xJ8E2HDWAIPk8H4I03pu3qeVyy2EaFg1xqv1ZJarO4Wv8YNsr//4twXG+eqOShc8uvexoup8VMm2OWVGCThEjOm6pKuUeuk90leJMRlOPl5y3Cg8dCSxOvMXDQnwHg7GtNkFR0YgJEqFj360Oy69/snU0GcbLhOEUgy76wgzXKvqgKB+zQhHonVlqAn+St1bHCBFTNOsRDm7BgrfoDALFWSFRBlnBMQ1WD7s8FDxNqpkCCiNc6eWqXTC+RUlKqVu8DFRBo+Ny7aZFsIIlra5lk3z2veRohOGnpfqVRz0gUtGixgxyEOEEH0sJfg="
    - secure: "fG2GyIyGAKhXnq+Ir9Nj/D+KI50LFC9uGwoJ8XkwN88LriVZrBoznEK7vE9DfbZI/tORZMe4bWrSVNWIPy1mSyqt5m582Lqviu7AvU1qqFsYj6LICDeKx4pnmcp0L+ky9wvj1nQeUgU8I56zO8lLaslJZnFD50rBnhR67x9EPhkgHSGMMWJMwzZiecLcdn//zm3i3lvkEOyYS8KuVXvgJpxQhi3EZSpFBGrE3CHissLkGGlgfTG7UrEXcm/lBo9PQd214fAO0QqDJvVqL5Jq69hlugGtMZDPQ/QHw1xo1Rf9pPCv/Gn5XsAuSJtewwXwBvEZZFJaaVAoFa5n5fTgWg3YH3QtDuJ3QiEtehy6Gz/fWM4xI99b2qADooRxCtJe5nDcNUolk2umXs43T6M00rMmWPaMzsIOpa84O3D3Qh4ptHkiKjqawh3EgVPUOHvWVRxvrjzvKNA58vlQvuxNYWJEngLOpv/GtF4UWMUYtduLOG1sIAPPuVx8E8RUwCJ7GG3fOrSrucLKd95/+SChmx1w2+WhdBqIxzM9ZDsr0+mLdDZjB2eqCYaLKpOC3zCgoVxpBUF6UAEB76i7F36xoOdtrIamRQ0t/RZga6juIOMtESj85wZ6aBBHsAuOF1AJPGw+GQwv8EdFtuTdKVe06xAT8ZoWPK5aa5QJyY1cpdY="
    - secure: "sExptXOKH3VcTULXF68o+NfH9i0K+3FMea0bcQVQzfRVGRjjh8b5YmXn+DX1GgmgUqkP6PY+iG83/BGDV8KXncEG5zjwyiRjddgecxBwFXejwbcZVx4BbXPofGJo15GozoXNtJWXiuJh75w2559xs/yyLlt19Dm/h0zkZ8ocCQ8NPyvVfdszA3DAEGMmG2bGX28uat0hXwufEDTdHcEt7fBst8rIALYcuByjiMO5s/g5jsUR9TPge2LCazPSlLzNkOnoTtruJ+az9zpAC8TpSdG0jSxfL6ECTWuYTBYA12Y/ZQqThcrhIF7bOuE1nfV4fvezfmZFYFVIDsEl+lB8r4IX56fo4gTWuOOdrKcsTgJBCkhjjEyrb1csTu+cK26m7b13CuC5S0d6CebXPOLngzcCRZdK1dGvsD9vLpOamj2HHXonf67DXW1Oho5GTyqyfbxSALrdwRAp9fu3JOGFa8JMXJn86RqxkHKLV+Z4+ll9wqyNFHkCW196yyMvl3weS1pJ2sHZSbvpbh8CABUcvUa9fJIoOhMIuzzvNgXboQ7P89bFJCBMDgQmPgGfdQ6jkbiyRtnYEdkOVHqylPiawQvdLS1BjuOmwvSNxOBqZ2t3XuaACS7mtrxi/6Pq2mPxvauLMcBBacoSetfIktu3gzWagxAX65s5cEO3AUfirLA="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - libiberty-dev
            - g++
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-unknown-linux-gnu
    - os: osx
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-apple-darwin
    - os: windows
      env: |
        TARGET=snowchains.exe
        RUSTUP_HOST=x86_64-pc-windows-msvc
      # https://travis-ci.community/t/windows-instances-hanging-before-install/250
      filter_secrets: false

install:
  - rustup self update
  - rustup set default-host $RUSTUP_HOST
  - rustup update $TRAVIS_RUST_VERSION
  - rustup component add clippy rustfmt
  - rustc --version --verbose
  - cargo --version --verbose
  - cargo clippy --version
  - rustfmt --version
  - |
    if [ "${RUSTUP_HOST}" = x86_64-unknown-linux-gnu -a "${TRAVIS_BRANCH}" = master -a "${TRAVIS_PULL_REQUEST}" = false ]; then
      cargo install cargo-kcov &&
      cargo kcov --print-install-kcov-sh | sh &&
      kcov --version &&
      cargo-kcov --version
    fi

script:
  - rustfmt --check ./proc_macros/src/lib.rs
  - cargo fmt --all -- --check
  # https://github.com/rust-lang/rust/issues/59909
  - bash -c 'cd ./proc_macros && cargo check'
  - cargo check
  - find ./src ./tests ./proc_macros/src -type f | xargs touch
  - bash -c 'cd ./proc_macros && cargo clippy -- -D warnings'
  - cargo clippy -- -D warnings
  - |
    if [ -f ~/.cargo/bin/cargo-kcov ]; then
      cargo kcov --all &&
      bash <(curl -s https://codecov.io/bash)
    elif [ "${TRAVIS_SECURE_ENV_VARS}" = true ]; then
      cargo test --all
    else
      cargo test --lib &&
      cargo test --test batch
    fi

before_deploy:
  - tar --version
  - tar --help
  - cargo build --release
  - mv ./target/release/$TARGET ./
  - cd $TRAVIS_BUILD_DIR/..
  - PROJECT="${TRAVIS_REPO_SLUG##*/}"
  - ZIP="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.zip"
  - TAR="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.tar.gz"
  - FILES="$PROJECT/$TARGET $PROJECT/LICENSE-MIT $PROJECT/LICENSE-APACHE $PROJECT/README.md"
  - |
    if [ "${TRAVIS_OS_NAME}" = windows ]; then
      7z a $ZIP $FILES &&
      7z l $ZIP &&
      mv $ZIP $TRAVIS_BUILD_DIR/
    else
      tar czvf $TAR $FILES &&
      mv $TAR $TRAVIS_BUILD_DIR/
    fi
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: "XAis0lOhyyMU7IjlDVTMcsOolG7ZYwBhKuTxX5pK82dgUmLijxgMVF3zcRifoWUuL9fXiDh6jDUkDPOFyv0SpUauMk5fVqvr7zmRKic1srRBsRFPW9UvOqDx5kg+MeO7NQJPFARyDzwNyl+Sb7WONslFfiysLW4YBruFgQCgaHay0G9icdRq9czJzKqAticLec7421w9bt9Rj3XmuoLck72AWbaT94H/hH0DTNHcZ4bIFfoZVW5D6swSGrUrNxrKQLbd40aJ8tNHZS/PnEnmsu0iS9NXbIwQys5w420MgP2mz3lg4c/FXf//2FjpgmKxFKEEbRnTw+BSjDWKxw2hJv1ojDNxsWymxfVwRdGWj2uXcRz9Lu1d49G1xxjnzak9Y+KYOKkAOeZ7RV0NUGWsUzT14trb7Ug4QEfp9tY1dKbZ4Nuos4+rreBjSyjUF70eXLncwWzNmuPnsmNcPa8jygQAqwAw01XMZu1grSRLmlOUW7eazpwp4WHgd66Hio0Y8mjQwZD+0pbedt1LND939vT/FrlOu6EYbRvCQpJSNBbfVB5ThZzaTrxZhHEq/IgHklSk3OELO0lOTox/jeZ2AKcoV2xZ7rscAUnbb4fJ9cR5IsXHIi2SfLKgGKqt5rlLU0f96C8uG3XUAWz1yi2Gr9afSGDbNYcD1GXPy2IjBH8="
  file: "*.{tar.gz,zip}"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: always

branches:
  only:
    - master
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
