dist: trusty
language: rust
sudo: true
addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable

env:
  global:
    - RUST_BACKTRACE=full
    - secure: "Pd/1aneEheqb/Wh43n70bSoiWQqcPHJTM5UkTwdvur1DNgab7G+qRRU6P27/9wPo9fkvc7+NfN6SEerX9sJu1pSVou/3b1l9cAqcgNWYln5dSOSmOU1x7LDOoVZxJrHBHxdQTMWW3LDsKHNrn/lRLVOkHba7QLf4AxAvC+oil8F02jnAMh8kaU5cPMrQ7Y+nF+qk1SXC5Sat1WnW5IamWN6pkh+YKQ8potA5C4Or3mN905hyqkKz1xyDq7pmpVjvM3eoMAWHQ6v94l5bqoUMfc9LBsPukYPpBbcbR9skuRJYehvw110LzPc1QQhdIrrWqXGKckeEPu+A87sRbVQor6lwKHVaOfmQOnbzUYOTqxPMMVNCvlAsy6DbfnLb7oUIwtS4cZipjmPxybAo5EsBip7ksg+st9jnEW9vW376TlNgu/2kgKGBWOJC05lC+o/YPC7ISa99Ls/+ctZWQps16Zal0nemsmmAytpvBGYwB0zooD0ow4M5I7k26qiZxorXnGcx7ZVkHOiOT4jGc09YMrJgp+0/wZ+5uci6BvW1e/jgz7scIMLGYIkUr0la7QUL2hsvABqFPHf4lHMJqhn6og4CqbRDQLSm6cLjL9pjKucQG4xcBC2Vmvo2br24Cfom6FoX64j5brp7/m02y7/wWptH+/hcIXsztlmLsS/S79Q="
    - secure: "rd1UiLdzPPMuH/CwQPkYBQSv/CvR2mXkDGANkvOpaGC4Ch0NQoaG+/LWylN/8GCEaWjkBkHvTqNvxcGqjt+MCbHmVoUPZ0T30HBxaLWE725r57bKi+yk6CT6g7YCqlMXMabaCMo07AjDKnIt0LrbBmdU7PFuYCZTkIu0Sl/DN/c+ZG1P5+n/m3J3L9MxVabTmfvs8xsxIBOjlPGxmOX7C7fgeDSVRcSjwvE7lZBZF5hVupXrsAgnU/Ts0K2i6EaMkC5Zj4A7KUNtK2sV9ucssdceemD+rG4TSdnc4wZbkxi/eyYdKVvY1WPo8vp0brC89ftmEMzGgt4Gcat1pNz5aNL3wXf6kPEmIQbWbYud2tEXti0X6hZIwiA0RO4o8i2dSH62M/SsOuyxGYzN+QEbeVOnLVljfFW59J3v5VcJCm5Ce9zswCJ9xRwlbG+D/UleCgn7Weq66Ke4VUlPoD5Xi9CWoV8gjhh0hZd9P/UeQ1wdUCt9lZNrUSPUMEBT2h2X+sru0zQ/+QoRgcHqbxp1ZVTTCWXBIOZA4Q5sTdh2OPtkzVv/yCEVoWqySi8zxEE9GommMeFUlQK8ZCa/kqA3TW57vYaBQPaCVxYCPJDSpcwkHeKwGQizT4MYjRaiSs9L0koeKh19jYPooa8N3wTo6p/6sZumPIubHJTlLkt1vdk="
    - secure: "o2T1i38r32YQW9W38xVFxp/0nZdkvkgb/LY8/co/a/RtXcKw6yY2cRBBYwaTIuUG8pVx/ilITBLE0iOHfwI9wKqOPD3/iYSQyY4liVyP/hlrikxewjMJQuxQ9Ul55d4Ik+XqGpCE/+i30Ct/TbTqp7ltKl7adShfMaryzZJ3HvuTmg6wiKDQDmlRRRqGJPPYs2qqGSQ2s7tAlESU413cLiCNFra96WqQYrVWgt7zvpf1uf+8EHq9SGxt9zvY9UKiZwqzglMvP4HO8T0km20B3Qjo6zW4e99YS7JmkVl04CA62kd8OyAn4x/fNSRug7+uyqW3ypVwo1/cP8/pnQUnYE+CvE/JuVUPMU5/GNTYCQogN3jUh54b67fxm03tTGxB1IcF23Kt/bWtFePsUfwdM2Dyc7mZ28zWgroIXGe9FGpn0sZEw/PzQALF5I9dRuk0AnnQnvXN6U77zaDd/IoO6fjrF02FTnIRoTAxEojdxVDTedKORw4K3WAXy10IAmo522/tFQS809Edyg2m/KxPyvjuZqHW9vJnAAquVlYuwQc65pCU87B1J57FKkZP2+/X2h9C53BrEAH1ELRuubetu+5eW+Vr/3jowlzLpmC84dDb3RZCPICDBGNYv+v5ilewSQwSVstshcEJYOPon0KVKuJzBvxGbJSbXfoJEzyu+8U="
    - secure: "rAw30hUB9zrAI2eCGFALKomDzSNOhA3zeEEar0hpr4bcRiY1pc6deahodnGI918na64uJ4U861RZ6eih7i8/93T5KYEY904+rF1rhK7YJJbFlLRbaphQeYjp5W3R09JR+4pwp3bXggl8k24Pw341PCDwJSo0hYIrTFWklnjL8nB4VwJwY1XC3DdHRKN8bbuqim0xr1wdPvDw28kSqY40cJ9i5EJIDd+zcF6GUIwYi3HTcaFpUYgT2dMHqWywAzmdhh15vuk5h2UZhXG9SiYhCcWO8GrrsrBVRcicreZki/G5y6QcT7eJ37MY2vmwym/dRHp8GfhsDRJPFq3Nl5LdYODLTiTeRrWL+xo07uZ0rEDJRs3cLmZblfJk42iiyVE/7euByKHWmzKJO5V+5nuJA4ManVLLwNKVvSIGf9+fWq2lrPbenky9W28MnWvcW8usxM0H5fXACgrWDwSUBqHLFuVXhqPMrf8EDYyKiep86RYrHJIze5UnLZ88bJZm25d8L0PxbpArgUlGyfe0b7hAjh7ZrfNC1TisvLp4z1qmE9xW5D28t7dTvzLxwc/cQss2L4maMpD7Ho8GTjs6V0YA3OF5wshciuPgmeLStQ5ZQZpfHaVpaXCKU2LO6bswBb4GWREsle9m9UezNw2ZNwfoU+qrx2nq1zk+p5UAvL8xiPE="

matrix:
  include:
    - os: linux
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-unknown-linux-gnu
    - os: osx
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-apple-darwin
    - os: windows
      env: |
        TARGET=snowchains.exe
        RUSTUP_HOST=x86_64-pc-windows-msvc

install:
  - rustup self update
  - rustup set default-host $RUSTUP_HOST
  - rustup update $TRAVIS_RUST_VERSION
  - rustup component add clippy rustfmt
  - rustc -vV
  - cargo -vV
  - cargo clippy -V
  - rustfmt -V
  - |
    if [ "${RUSTUP_HOST}" = x86_64-unknown-linux-gnu -a "${TRAVIS_BRANCH}" = master -a "${TRAVIS_PULL_REQUEST}" = false ]; then
      rustup install nightly &&
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo +nightly install cargo-tarpaulin &&
      rustc +nightly -vV &&
      cargo +nightly -vV &&
      cargo +nightly tarpaulin -V
    fi

script:
  - cargo fmt -- --check
  - rustfmt --check ./proc_macros/src/lib.rs
  - sh -c 'cd ./proc_macros && cargo clippy -- -D warnings'
  - cargo clippy --all-targets -- -D warnings
  - |
    if [ -f ~/.cargo/bin/cargo-tarpaulin ]; then
      cargo tarpaulin --ignored --out Xml &&
      bash <(curl -s https://codecov.io/bash)
    elif [ "${TRAVIS_SECURE_ENV_VARS}" = true ]; then
      cargo test --all
    else
      cargo test --lib &&
      cargo test --test batch
    fi

before_deploy:
  - tar --version
  - tar --help
  - cargo build --release
  - mv ./target/release/$TARGET ./
  - cd $TRAVIS_BUILD_DIR/..
  - PROJECT="${TRAVIS_REPO_SLUG##*/}"
  - ZIP="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.zip"
  - TAR="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.tar.gz"
  - FILES="$PROJECT/$TARGET $PROJECT/LICENSE $PROJECT/README.md"
  - |
    if [ "${TRAVIS_OS_NAME}" = windows ]; then
      7z a $ZIP $FILES &&
      7z l $ZIP &&
      mv $ZIP $TRAVIS_BUILD_DIR/
    else
      tar czvf $TAR $FILES &&
      mv $TAR $TRAVIS_BUILD_DIR/
    fi
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: "XAis0lOhyyMU7IjlDVTMcsOolG7ZYwBhKuTxX5pK82dgUmLijxgMVF3zcRifoWUuL9fXiDh6jDUkDPOFyv0SpUauMk5fVqvr7zmRKic1srRBsRFPW9UvOqDx5kg+MeO7NQJPFARyDzwNyl+Sb7WONslFfiysLW4YBruFgQCgaHay0G9icdRq9czJzKqAticLec7421w9bt9Rj3XmuoLck72AWbaT94H/hH0DTNHcZ4bIFfoZVW5D6swSGrUrNxrKQLbd40aJ8tNHZS/PnEnmsu0iS9NXbIwQys5w420MgP2mz3lg4c/FXf//2FjpgmKxFKEEbRnTw+BSjDWKxw2hJv1ojDNxsWymxfVwRdGWj2uXcRz9Lu1d49G1xxjnzak9Y+KYOKkAOeZ7RV0NUGWsUzT14trb7Ug4QEfp9tY1dKbZ4Nuos4+rreBjSyjUF70eXLncwWzNmuPnsmNcPa8jygQAqwAw01XMZu1grSRLmlOUW7eazpwp4WHgd66Hio0Y8mjQwZD+0pbedt1LND939vT/FrlOu6EYbRvCQpJSNBbfVB5ThZzaTrxZhHEq/IgHklSk3OELO0lOTox/jeZ2AKcoV2xZ7rscAUnbb4fJ9cR5IsXHIi2SfLKgGKqt5rlLU0f96C8uG3XUAWz1yi2Gr9afSGDbNYcD1GXPy2IjBH8="
  file: "*.{tar.gz,zip}"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: always

branches:
  only:
    - master
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
