dist: trusty
language: rust
sudo: true
addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable

env:
  global:
    - RUST_BACKTRACE=full
    - ATCODER_USERNAME=wariuni
    - secure: "rd1UiLdzPPMuH/CwQPkYBQSv/CvR2mXkDGANkvOpaGC4Ch0NQoaG+/LWylN/8GCEaWjkBkHvTqNvxcGqjt+MCbHmVoUPZ0T30HBxaLWE725r57bKi+yk6CT6g7YCqlMXMabaCMo07AjDKnIt0LrbBmdU7PFuYCZTkIu0Sl/DN/c+ZG1P5+n/m3J3L9MxVabTmfvs8xsxIBOjlPGxmOX7C7fgeDSVRcSjwvE7lZBZF5hVupXrsAgnU/Ts0K2i6EaMkC5Zj4A7KUNtK2sV9ucssdceemD+rG4TSdnc4wZbkxi/eyYdKVvY1WPo8vp0brC89ftmEMzGgt4Gcat1pNz5aNL3wXf6kPEmIQbWbYud2tEXti0X6hZIwiA0RO4o8i2dSH62M/SsOuyxGYzN+QEbeVOnLVljfFW59J3v5VcJCm5Ce9zswCJ9xRwlbG+D/UleCgn7Weq66Ke4VUlPoD5Xi9CWoV8gjhh0hZd9P/UeQ1wdUCt9lZNrUSPUMEBT2h2X+sru0zQ/+QoRgcHqbxp1ZVTTCWXBIOZA4Q5sTdh2OPtkzVv/yCEVoWqySi8zxEE9GommMeFUlQK8ZCa/kqA3TW57vYaBQPaCVxYCPJDSpcwkHeKwGQizT4MYjRaiSs9L0koeKh19jYPooa8N3wTo6p/6sZumPIubHJTlLkt1vdk="
    - secure: "o2T1i38r32YQW9W38xVFxp/0nZdkvkgb/LY8/co/a/RtXcKw6yY2cRBBYwaTIuUG8pVx/ilITBLE0iOHfwI9wKqOPD3/iYSQyY4liVyP/hlrikxewjMJQuxQ9Ul55d4Ik+XqGpCE/+i30Ct/TbTqp7ltKl7adShfMaryzZJ3HvuTmg6wiKDQDmlRRRqGJPPYs2qqGSQ2s7tAlESU413cLiCNFra96WqQYrVWgt7zvpf1uf+8EHq9SGxt9zvY9UKiZwqzglMvP4HO8T0km20B3Qjo6zW4e99YS7JmkVl04CA62kd8OyAn4x/fNSRug7+uyqW3ypVwo1/cP8/pnQUnYE+CvE/JuVUPMU5/GNTYCQogN3jUh54b67fxm03tTGxB1IcF23Kt/bWtFePsUfwdM2Dyc7mZ28zWgroIXGe9FGpn0sZEw/PzQALF5I9dRuk0AnnQnvXN6U77zaDd/IoO6fjrF02FTnIRoTAxEojdxVDTedKORw4K3WAXy10IAmo522/tFQS809Edyg2m/KxPyvjuZqHW9vJnAAquVlYuwQc65pCU87B1J57FKkZP2+/X2h9C53BrEAH1ELRuubetu+5eW+Vr/3jowlzLpmC84dDb3RZCPICDBGNYv+v5ilewSQwSVstshcEJYOPon0KVKuJzBvxGbJSbXfoJEzyu+8U="
    - secure: "C3VPj+T+d83fNuELFmyT4R/1DZoRqkShscapID+Q/gpOng6dnLif3Ya+QhUh7OD/GibYkr835z7Akm3FMuUfInAHPT9WuB3v/WomRG/8Z0l7nby0vI2gBQcu3ga5kkt1pKiWCS3DDDKiiyK/SzoaN1FEpPZX4b6MJYPGU0VF3pihqOVZJ02DBwm7wcCnsiMtahGRAaxiYhbpAmLhDAENt315NXtoZku2+gLQIEjdr88m1r1wayG9IU/9bOfnkE62wb6wly4Yl0CKWwp3U917lMYLZkkK8j0SZh3RVwHvIIwcw7X6GO8L/jxYwYtxYOI4WAXk4ULW9yg1Cm1A36evuSn2gPx1wJ9li5Bj+/NYSWRvgEZTAUD/sYOpOy5TEFUlwfRLoBeF7G/f0RHOhb+wqvWDydTMukacg6xEKOUpMBWNtERL/NCWDeBVrU3pAXKbZHqwDXTsvY/0u7K3pP7uFv9HF0noqXO07+0otHe8sG9fsrMaU/BSujEu63tg2zhBimpmMHsG7pppP9RG5VWF3v01OeCwhza6Esmj/KIy/3oVvWQUkwT2M/dBw/j2re+VhCsTcpXZr0c0RNWiTYIS19s6RK5ssm0ZKMRSQrHBDrkezFbyatXYTBg4yc4J7YklvwfqeA4ivPH/DnyrDPm2FW0i70MCaPjaddJkgHQPIbk="

matrix:
  include:
    - os: linux
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-unknown-linux-gnu
    - os: osx
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-apple-darwin
    - os: windows
      env: |
        TARGET=snowchains.exe
        RUSTUP_HOST=x86_64-pc-windows-msvc
      # https://travis-ci.community/t/windows-instances-hanging-before-install/250
      filter_secrets: false

install:
  - rustup self update
  - rustup set default-host $RUSTUP_HOST
  - rustup update $TRAVIS_RUST_VERSION
  - rustup component add clippy rustfmt
  - cargo install --debug cargo-make
  - rustc --version --verbose
  - cargo --version --verbose
  - cargo clippy --version
  - rustfmt --version
  - cargo make --version
  - |
    if [ "${RUSTUP_HOST}" = x86_64-unknown-linux-gnu -a "${TRAVIS_BRANCH}" = master -a "${TRAVIS_PULL_REQUEST}" = false ]; then
      rustup install nightly &&
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo +nightly install cargo-tarpaulin &&
      rustc +nightly -vV &&
      cargo +nightly -vV &&
      cargo +nightly tarpaulin -V
    fi

script:
  - cargo make check-format
  - cargo make clippy
  - |
    if [ -f ~/.cargo/bin/cargo-tarpaulin ]; then
      cargo tarpaulin --ignored --out Xml &&
      bash <(curl -s https://codecov.io/bash)
    elif [ "${TRAVIS_SECURE_ENV_VARS}" = true ]; then
      cargo test --all
    else
      cargo test --lib &&
      cargo test --test batch
    fi

before_deploy:
  - tar --version
  - tar --help
  - cargo build --release
  - mv ./target/release/$TARGET ./
  - cd $TRAVIS_BUILD_DIR/..
  - PROJECT="${TRAVIS_REPO_SLUG##*/}"
  - ZIP="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.zip"
  - TAR="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.tar.gz"
  - FILES="$PROJECT/$TARGET $PROJECT/LICENSE $PROJECT/README.md"
  - |
    if [ "${TRAVIS_OS_NAME}" = windows ]; then
      7z a $ZIP $FILES &&
      7z l $ZIP &&
      mv $ZIP $TRAVIS_BUILD_DIR/
    else
      tar czvf $TAR $FILES &&
      mv $TAR $TRAVIS_BUILD_DIR/
    fi
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: "XAis0lOhyyMU7IjlDVTMcsOolG7ZYwBhKuTxX5pK82dgUmLijxgMVF3zcRifoWUuL9fXiDh6jDUkDPOFyv0SpUauMk5fVqvr7zmRKic1srRBsRFPW9UvOqDx5kg+MeO7NQJPFARyDzwNyl+Sb7WONslFfiysLW4YBruFgQCgaHay0G9icdRq9czJzKqAticLec7421w9bt9Rj3XmuoLck72AWbaT94H/hH0DTNHcZ4bIFfoZVW5D6swSGrUrNxrKQLbd40aJ8tNHZS/PnEnmsu0iS9NXbIwQys5w420MgP2mz3lg4c/FXf//2FjpgmKxFKEEbRnTw+BSjDWKxw2hJv1ojDNxsWymxfVwRdGWj2uXcRz9Lu1d49G1xxjnzak9Y+KYOKkAOeZ7RV0NUGWsUzT14trb7Ug4QEfp9tY1dKbZ4Nuos4+rreBjSyjUF70eXLncwWzNmuPnsmNcPa8jygQAqwAw01XMZu1grSRLmlOUW7eazpwp4WHgd66Hio0Y8mjQwZD+0pbedt1LND939vT/FrlOu6EYbRvCQpJSNBbfVB5ThZzaTrxZhHEq/IgHklSk3OELO0lOTox/jeZ2AKcoV2xZ7rscAUnbb4fJ9cR5IsXHIi2SfLKgGKqt5rlLU0f96C8uG3XUAWz1yi2Gr9afSGDbNYcD1GXPy2IjBH8="
  file: "*.{tar.gz,zip}"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: always

branches:
  only:
    - master
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
