language: rust

rust:
  - stable

env:
  global:
    - RUST_BACKTRACE=full
    - secure: "lH0uIumC+VdEZ7P9jaSWNn06OFhjj6gIZHQYQkBftfh5hDussnOSSEV1aWsZddpUXBkeioSKkv3tlA/UkOMI7SazMfwaWuxTy7fJZTBSaDkbE3Wyfi1wXCTEFi/XQ1KpYOxafYKF9DsPcWK1Dvdoz7H89jvuoXed1TrQUaZZa9IEOW0OwUK20+BsWe373JNUsCGXAvf+DMxvHSZ/8irc5hp/5tfaiL47Ds1iWvqFReFhZ8/bnz9F54oG/A9+uUp/FtbGweay7zI1bZPnNgnjAHsnTNaYkz49uEnz+45z07XYC3jWe21aRuuPLgpr8Y49ou0cdN4kgDHj1JBWTwle7f7eD4bB1LjbL7jIFqjxh4FWj6N5qt2NKguECfqPCXcqjTqCr/NKnK3tbggoEfnZSoCzFB79PYoEM9GCCx3XylBesURqsyFR8rWiUQeqv0SCWhga5t/n6FovTx+YVVDfnjpX6W2DXXr0VGiIx5o5WXj7qAYXHKpFod6YPKMdS9lptZ6SIsxBMAbXXG60eBBHFT9gZE36Si1SBkT5hhK1aDfFPGRZaXdtgawwMOjqcUvPao5f8PdgEC0rHxMDruoXfcUsSd2pyGksjV7wBO5Q0vtDw/Wbde1euyGemyxlmlZOKSNtChEVVDB0wtn0ZQYbHs1gPZ0jmFGC6PaFa6b2yRs="
    - secure: "rd1UiLdzPPMuH/CwQPkYBQSv/CvR2mXkDGANkvOpaGC4Ch0NQoaG+/LWylN/8GCEaWjkBkHvTqNvxcGqjt+MCbHmVoUPZ0T30HBxaLWE725r57bKi+yk6CT6g7YCqlMXMabaCMo07AjDKnIt0LrbBmdU7PFuYCZTkIu0Sl/DN/c+ZG1P5+n/m3J3L9MxVabTmfvs8xsxIBOjlPGxmOX7C7fgeDSVRcSjwvE7lZBZF5hVupXrsAgnU/Ts0K2i6EaMkC5Zj4A7KUNtK2sV9ucssdceemD+rG4TSdnc4wZbkxi/eyYdKVvY1WPo8vp0brC89ftmEMzGgt4Gcat1pNz5aNL3wXf6kPEmIQbWbYud2tEXti0X6hZIwiA0RO4o8i2dSH62M/SsOuyxGYzN+QEbeVOnLVljfFW59J3v5VcJCm5Ce9zswCJ9xRwlbG+D/UleCgn7Weq66Ke4VUlPoD5Xi9CWoV8gjhh0hZd9P/UeQ1wdUCt9lZNrUSPUMEBT2h2X+sru0zQ/+QoRgcHqbxp1ZVTTCWXBIOZA4Q5sTdh2OPtkzVv/yCEVoWqySi8zxEE9GommMeFUlQK8ZCa/kqA3TW57vYaBQPaCVxYCPJDSpcwkHeKwGQizT4MYjRaiSs9L0koeKh19jYPooa8N3wTo6p/6sZumPIubHJTlLkt1vdk="
    - secure: "o2T1i38r32YQW9W38xVFxp/0nZdkvkgb/LY8/co/a/RtXcKw6yY2cRBBYwaTIuUG8pVx/ilITBLE0iOHfwI9wKqOPD3/iYSQyY4liVyP/hlrikxewjMJQuxQ9Ul55d4Ik+XqGpCE/+i30Ct/TbTqp7ltKl7adShfMaryzZJ3HvuTmg6wiKDQDmlRRRqGJPPYs2qqGSQ2s7tAlESU413cLiCNFra96WqQYrVWgt7zvpf1uf+8EHq9SGxt9zvY9UKiZwqzglMvP4HO8T0km20B3Qjo6zW4e99YS7JmkVl04CA62kd8OyAn4x/fNSRug7+uyqW3ypVwo1/cP8/pnQUnYE+CvE/JuVUPMU5/GNTYCQogN3jUh54b67fxm03tTGxB1IcF23Kt/bWtFePsUfwdM2Dyc7mZ28zWgroIXGe9FGpn0sZEw/PzQALF5I9dRuk0AnnQnvXN6U77zaDd/IoO6fjrF02FTnIRoTAxEojdxVDTedKORw4K3WAXy10IAmo522/tFQS809Edyg2m/KxPyvjuZqHW9vJnAAquVlYuwQc65pCU87B1J57FKkZP2+/X2h9C53BrEAH1ELRuubetu+5eW+Vr/3jowlzLpmC84dDb3RZCPICDBGNYv+v5ilewSQwSVstshcEJYOPon0KVKuJzBvxGbJSbXfoJEzyu+8U="
    - secure: "Y4h8/zJm6/cuRiMXM9I7RMRlUtHVYgGDV8O7gIEDVmDj1imIFfy0lDlfFYCbeIO2rwDODs+fDcP+BV/OXwiW09UWHQGCDaOsm56WhbZRrX2FKIRfBvzPy38OuXtY5AvFZTvuLx2Qza4G8Uq2gpIXYUD4t9mjlcbAPtFv73sS9PRHpq4FlKnrzETtpP6NOSMWp4HGJ04kGkJ0Io99dT7yB8bysy+uWSXmNJqKA/XGf2SvPtD/q8KTUzJX4d56Fw/Uz2cSV+maLrsIF+xqVzaqfhMvbeOlxaBu7NDpfW6OwQQz1yejSd7eywlKwhOwBz2hzXsdvRFHSTq5pS1wCZMTkjpCLb1HOH4IuXDmmVy9OPvSVh+0yIiuiYQ95ezzabn5XvBbn6RLMWki0d0VWwA8y2MWjWR5ZG89vNpcma9EKGLozcJFoZt/nsJuCX0NaHRIhe2OqyRJGd/LBasJBoP0XCu42OqrJCbU/hbmkY537mWyKLn6WR+0jujpN71grKS1pZppiJb7RAXUfnKSx6rd3qzUdUV0/lhk0i9/oV5R9B5DfY/HHWyvziO0ZdM3ie4CqC2FbpfZcEpd3uJZkFoQoUfS/dwO9xe3V7Ynprh/9TJ5JnYbmpol2uwVDG9+N3kGlymhq9pazCn+AKxjs0Sq0eD2xnP14Dj1VFjKtWrDVZA="
    - secure: "e4nfNyRHPHalApditzfYrNc9D2mOp5slz0X87W/qnhl+hM9SOG3BuABn590tSfT2eMrMLN0uodZogXRxYnr/A4ZpBoVRur9IxN8XgkMuOH9ZJzfx5nGI9MMmN7ffKQDfrYr9Q+YuCkWBx81a414CQDASCBtJt+/oC2+pkhA9N7RRqm+yz2NGvgFIvTMhikSLIXKDkiXkEZNcN/FO1V4upOfvdI7EilUmB8uUTKUvqb+PuqRuvXEPoLWLvNJqhQljs0A2VR8yqAIURrIAjcZzp3JZ3aO+v7FzB1obHCZzU14GgDbn1uIMA11mj+guGOhuXbrFo5tw5B62gBo4IpsS8u71Cx8oH1rHcqQ0BE4fQxT3dnCRD7s31Nbj5LcokC2mt6XqChAi8cWRZA3raycA/OQlgM9QF0B/PAV6QPDZFzxkuqKu55T0BmcSqecwq1OWohdBYoqfALqr0QII53Su1UjVbtPxCj5SAVYzp3DyErCGWxs5Wh7VElBvYsk32/SYtIQZiTpmq7Xdogm86alqGOFdp+rVZUHBF5cGzVyIgiKn/2nQ7bvumb5+tWe3Cmr3Iolgd2UVOqs6gCpdzj1GSgs20Ia5DJ3zXBC5FXJPey0LunvPhS0rtXxKhMGGeXNZXjbnW1vE0VrgFlZMncyNS7/54X4QkTJyvPFNYZMs2pU="
    - secure: "vjphenN0rtxQqCgZ75nUtf62tQAmmSQA0Iqna2g5/hm8mVJcjDalNGh5iuXNAfI/pMsU9NXeUUaUfxEj323AcxlDqbS55kBAZimQ/ySOdyL/gCoUQOnr7HvThZakbNKeQwivUa3UR0cVPFFKI582wIvnxXOB3qxA/G15Vdhl+Q8HAH0jcfDZunUSlqnlxGi7GLMuTR+5OjP+SZFgxR+3DMjHBbjX841c8PVWu8WywXydH0x5Jcn3SgvVpQJgHXptllzKZ+Tp1TNDbRdAYTuJmgKwipe3/wW0SI/XO9HKSqdA/mjQtjNpwzOcg8FYkTypNwMlpciHVKbuJa9rdnoKR8mW6eEyfSMnSfeDGcAff5bHs8n1syN6MQ1yo0b9VCQ3jFe/jOFw9rlulTmBYjF4xpDG+GARsCrDT3HihF5U8Z4p3rzIaKc84fs797pFOp5K/2Mpf65YAPnWYCTB88ViYuzPA7ENWvB8y/5ut9K2m3A9nmbs4UV/jEHRkNMyd58uDOLFCdagwhyGjbR9xBb++viWAgZ4+W3gXJTWKAOr4dVIDf/5Te/pfOmSSxStlQLmIglDwvAsKtJi9lN5vrAJRyPZPyFhMtkJkk6VP5g7i8hCY9MRahN8HAtxZU57UO3d1OCl5nGWdIiXQ9/ikG7a/xEd5IGhGfkm7xgrpwp8juI="
    - secure: "EP4m2Qn5p++P/KzMItpZiDpMtpPvrbV8oEtcIzff3XTeE3zh2NiFC2PpLTFYmD6CPPI4tl8Ll5z92pTp4pPJ2NgY5jGNR9CtT39elWDyDdxWTXxf+/e09t9m4CrK3iyxZciT7rQV3dRywljTjB1ch9PwDo8anWekaOz8gDDaFrTMByZSYZ8ARCmgp+4zutj/pMWmJUUxkf5VvCGhmPDYqLN2zf68NMJga0fqfXIN4JKw4fmp9NyWgNkqfAfkjvj5DJjnGSKMUQI4Ab1GtcwD/cACCfdHBYGbLnYmAgfR9oryxcLayaRCMLNpG3ktgdIIIvvOXnzPTAM0Wav81N2Ukt3dBebXfaeZ/97+DmeVmOniSNT7Qg+0HKwp+g04j1sjwZPqVDfW0kBcKztx0SA59b3i8GOEZfZwui1+GPQcUdHlPhSD2I824SaBHUbJveMsloNZN6X4FDiPA5cpOtWeYjp8u4CsMaQTNWVBEHS2KQcmK2dhu8grbd1LEL/NZgfDVcC2UhJOQnwy+WVHtk0G2rikFeAHpxx1MCf+QFQ3dUEnA/IAuTgMB99wlpKhRUhB6JJv70+TiteoXZ4LE77BPyYbfXx8YfmK22rTe92cksZKETw0mr7DzGDhvlVtPYy7VHCp4pTegdjoboUNfYxKjdpu6xPP4WpHs7p1PLdGbrU="
    - secure: "pBxJyP1GEBV/EWML+SmvEaYPU5ItBEiyxq83JsudPzMViRC9ZViA4cBQvs2lvQP3HABG8BngwSc11BIxdhIjBh0I5Z30jXgnQnUSx071CwqPwyilnwMwTdd+F9U37reTTsPrqHz+B1zPcex3383rSCOdXBjTfVPO3rPTgLzDPoTMD7LEbbQPOGsY/W0S2x6D8Vx9S3fBQlQXR6UFRrPzr1eTgTqZxHQPlN4nOyg9xSP7gGr82beXfuafZoaCtb9NT6gnX0CfHEjNnFYrpp5ijFyBmWEDROhbpVPg8syYPzhwGqkyIyliMez6nj3AkgCT6tulAysVAPByRpxmG8VAqp0Aoco9H06S9JmdS1oQq/ElE47YZu0YwbBNMweHvdfEDh6ddMSjxAjLkvQmatHWmX83Tr9t4hl/eKpdaTErM+c1KsWIWJPMXS/mwKAb3hqWQ8BgwaJrcnZrlGEe04y6nLKPZ4JOqd9W6XufjBE/ld73VPxnDsODLxD5S9mrjeLG389C3OrV+WxXw9l/R20S7l0RkHFDsSzSx+gxdYfnCnpg0t9V1oQVMA98oxUlki5HSbH/2g87KV4Q3DpnvmxBiNvQSHJ8xBWzS0D6tyBwoB+unJgIPFVPiGmQFhVFF06axvJBUVBY58vqgZxVyDAiZX8Oji2kC1pumcYg5vuLpaM="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - libiberty-dev
            - g++
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-unknown-linux-gnu
    - os: osx
      env: |
        TARGET=snowchains
        RUSTUP_HOST=x86_64-apple-darwin
    - os: windows
      env: |
        TARGET=snowchains.exe
        RUSTUP_HOST=x86_64-pc-windows-msvc
      # https://travis-ci.community/t/windows-instances-hanging-before-install/250
      filter_secrets: false

install:
  - rustup self update
  - rustup set default-host $RUSTUP_HOST
  - rustup update $TRAVIS_RUST_VERSION
  - rustup component add clippy rustfmt
  - rustc --version --verbose
  - cargo --version --verbose
  - cargo clippy --version
  - rustfmt --version
  - |
    if [ "${RUSTUP_HOST}" = x86_64-unknown-linux-gnu -a "${TRAVIS_BRANCH}" = master -a "${TRAVIS_PULL_REQUEST}" = false ]; then
      cargo install cargo-kcov &&
      cargo kcov --print-install-kcov-sh | sh &&
      kcov --version &&
      cargo-kcov --version
    fi

script:
  - rustfmt --check ./proc_macros/src/lib.rs
  - cargo fmt --all -- --check
  # https://github.com/rust-lang/rust/issues/59909
  - bash -c 'cd ./proc_macros && cargo check'
  - cargo check
  - find ./src ./tests ./proc_macros/src -type f | xargs touch
  - bash -c 'cd ./proc_macros && cargo clippy -- -D warnings'
  - cargo clippy -- -D warnings
  - |
    if [ -f ~/.cargo/bin/cargo-kcov ]; then
      cargo kcov --all &&
      bash <(curl -s https://codecov.io/bash)
    elif [ "${TRAVIS_SECURE_ENV_VARS}" = true ]; then
      cargo test --all
    else
      cargo test --lib &&
      cargo test --test batch
    fi

before_deploy:
  - tar --version
  - tar --help
  - cargo build --release
  - mv ./target/release/$TARGET ./
  - cd $TRAVIS_BUILD_DIR/..
  - PROJECT="${TRAVIS_REPO_SLUG##*/}"
  - ZIP="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.zip"
  - TAR="$PROJECT-$TRAVIS_TAG-$RUSTUP_HOST.tar.gz"
  - FILES="$PROJECT/$TARGET $PROJECT/LICENSE-MIT $PROJECT/LICENSE-APACHE $PROJECT/README.md"
  - |
    if [ "${TRAVIS_OS_NAME}" = windows ]; then
      7z a $ZIP $FILES &&
      7z l $ZIP &&
      mv $ZIP $TRAVIS_BUILD_DIR/
    else
      tar czvf $TAR $FILES &&
      mv $TAR $TRAVIS_BUILD_DIR/
    fi
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: "XAis0lOhyyMU7IjlDVTMcsOolG7ZYwBhKuTxX5pK82dgUmLijxgMVF3zcRifoWUuL9fXiDh6jDUkDPOFyv0SpUauMk5fVqvr7zmRKic1srRBsRFPW9UvOqDx5kg+MeO7NQJPFARyDzwNyl+Sb7WONslFfiysLW4YBruFgQCgaHay0G9icdRq9czJzKqAticLec7421w9bt9Rj3XmuoLck72AWbaT94H/hH0DTNHcZ4bIFfoZVW5D6swSGrUrNxrKQLbd40aJ8tNHZS/PnEnmsu0iS9NXbIwQys5w420MgP2mz3lg4c/FXf//2FjpgmKxFKEEbRnTw+BSjDWKxw2hJv1ojDNxsWymxfVwRdGWj2uXcRz9Lu1d49G1xxjnzak9Y+KYOKkAOeZ7RV0NUGWsUzT14trb7Ug4QEfp9tY1dKbZ4Nuos4+rreBjSyjUF70eXLncwWzNmuPnsmNcPa8jygQAqwAw01XMZu1grSRLmlOUW7eazpwp4WHgd66Hio0Y8mjQwZD+0pbedt1LND939vT/FrlOu6EYbRvCQpJSNBbfVB5ThZzaTrxZhHEq/IgHklSk3OELO0lOTox/jeZ2AKcoV2xZ7rscAUnbb4fJ9cR5IsXHIi2SfLKgGKqt5rlLU0f96C8uG3XUAWz1yi2Gr9afSGDbNYcD1GXPy2IjBH8="
  file: "*.{tar.gz,zip}"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: always

branches:
  only:
    - master
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
