clone_depth: 1
environment:
  matrix:
  - HOST: x86_64-pc-windows-msvc
    TOOLCHAIN: stable
  - HOST: x86_64-pc-windows-gnu
    TOOLCHAIN: stable
  - HOST: i686-pc-windows-msvc
    TOOLCHAIN: stable
  - HOST: i686-pc-windows-gnu
    TOOLCHAIN: stable
  - HOST: x86_64-pc-windows-msvc
    TOOLCHAIN: beta
  - HOST: x86_64-pc-windows-gnu
    TOOLCHAIN: beta
  - HOST: i686-pc-windows-msvc
    TOOLCHAIN: beta
  - HOST: i686-pc-windows-gnu
    TOOLCHAIN: beta
  - HOST: x86_64-pc-windows-msvc
    TOOLCHAIN: nightly
  - HOST: x86_64-pc-windows-gnu
    TOOLCHAIN: nightly
  - HOST: i686-pc-windows-msvc
    TOOLCHAIN: nightly
  - HOST: i686-pc-windows-gnu
    TOOLCHAIN: nightly
matrix:
  allow_failures:
    - HOST: i686-pc-windows-msvc # https://github.com/tokio-rs/tokio-timer/issues/43
    - HOST: i686-pc-windows-gnu
    - TOOLCHAIN: nightly
install:
  - ps: >-
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/${env:HOST}/rustup-init.exe"
  - rustup-init.exe -y --default-toolchain %TOOLCHAIN% --default-host %HOST% --no-modify-path
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV
test_script:
  - cargo +%TOOLCHAIN% test -v
  - cargo +%TOOLCHAIN% test -v -- --ignored
build_script:
  - cargo +%TOOLCHAIN% build --release
  - ps: New-Item snowchains -itemType Directory
  - ps: >-
      $ZIP = "snowchains-${env:APPVEYOR_REPO_TAG_NAME}-${env:HOST}.zip";
      Copy-Item "target\${env:TARGET}\release\snowchains.exe" '.\snowchains\';
      Copy-Item README.md '.\snowchains\';
      Copy-Item LICENSE '.\snowchains\';
      7z a "$ZIP" snowchains
deploy:
  - provider: GitHub
    auth_token:
      secure: khL++opdJh5x79PMMTkOJXPXi8D+ijp0os5Bi02rA4DSApOmuF1VuZWpIzyDZ8pi
    on:
      appveyor_repo_tag: true
      TOOLCHAIN: stable
artifacts:
  path: '*.zip'
cache:
  - C:\Users\appveyor\.cargo\registry
  - target
branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master
notifications:
  - provider: Email
    on_build_success: false
