image: Visual Studio 2015

platform: x86_64

environment:
  global:
    TARGET: snowchains.exe
    RUSTUP_TOOLCHAIN: stable
    RUSTUP_HOST: x86_64-pc-windows-msvc
    RUST_BACKTRACE: full
    ATCODER_USERNAME:
      secure: koc3zc/wQPQvMQj1hJCjKQ==
    ATCODER_PASSWORD:
      secure: zndOc4jqvw5aigjpDnoUSEycIHdwddCYtI8gh/o2yBvDnL3GIT0ea0YavFmdMDMA
    DROPBOX_ACCESS_TOKEN:
      secure: raJjp7/0JOOrG5bJDGVFFA+HLPqkxG4b3+XnxY7ZZSisX/x6pOTCEuJ8Yb//ejTfJk4h8DIT1lDwIVf9C2lnvvtlJQSEb9bPt6VCBL98xN4=
    HACKERRANK_USERNAME:
      secure: H8+ut9G/t8aUFXYcBHGA/VRYHBZ0jDA/vnNYTUlbZ+Q=
    HACKERRANK_PASSWORD:
      secure: YCYQSV4TkGO8oHAkURbWzb6P57lzjE7NxUxy/c1XA2E=
    YUKICODER_REVEL_SESSION:
      secure: Kk65uDuSdkh+HJCLh72JBK1gPjAJMFHkONVBtK1nVQRhddSIVToWe/nCDrDOa0X2IMaoY/l3yBo3kN88nP3u23WVYzvBY6SnEHbfzD3+DRB2ezo4SDjfnBQENj+JEfd4P0yqcu2srbZIF/8WmwwDwJZaOMt7CUUKkMVeoqQt2W9/avX9ed7WtU639xGiX7A3BV5e0/wHnGRmoehhQN63STq9x2ARQCEuNs+3MCFpaInOtCauI+QxK4YaYzyx86Rd2/dNrIYbE6LIz6K83IyKMg==

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/${env:RUSTUP_HOST}/rustup-init.exe"
  - rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN% --default-host %RUSTUP_HOST% --no-modify-path
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  - rustup component add clippy-preview rustfmt-preview
  - rustc -vV
  - cargo -vV
  - cargo clippy -V
  - rustfmt -V

build: false

test_script:
  - cargo fmt --all -- --check
  - cmd /C "cd .\proc_macros && cargo clippy -- -D warnings"
  - cargo clippy --all-targets -- -D warnings
  - ps: $env:targets = If (Test-Path env:ATCODER_USERNAME) { 'all' } else { 'lib' }
  - cargo test --%targets%

before_deploy:
  - cargo build --release
  - ps: Move-Item "target\release\${env:TARGET}" .\
  - cd C:\projects
  - ps: |
      $ZIP = "${env:APPVEYOR_BUILD_FOLDER}/${env:APPVEYOR_PROJECT_NAME}-${env:APPVEYOR_REPO_TAG_NAME}-${env:RUSTUP_HOST}.zip"
      7z a "$ZIP" "${env:APPVEYOR_PROJECT_NAME}/${env:TARGET}" "${env:APPVEYOR_PROJECT_NAME}/LICENSE" "${env:APPVEYOR_PROJECT_NAME}/README.md"
      7z l "$ZIP"
      Push-AppveyorArtifact "$ZIP"
  - cd %APPVEYOR_BUILD_FOLDER%

deploy:
  - provider: GitHub
    artifact: /^.*\.zip$/
    auth_token:
      secure: khL++opdJh5x79PMMTkOJXPXi8D+ijp0os5Bi02rA4DSApOmuF1VuZWpIzyDZ8pi
    on:
      appveyor_repo_tag: true

cache:
  - '%HOME%\.cargo\git'
  - '%HOME%\.cargo\registry\index'
  - '%HOME%\.cargo\registry\src'

notifications:
  - provider: Email
    on_build_success: true
    on_build_failure: true

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
