image: Visual Studio 2017
environment:
  global:
    TARGET: snowchains.exe
    RUSTUP_TOOLCHAIN: stable
    RUST_BACKTRACE: full
    ATCODER_USERNAME:
      secure: koc3zc/wQPQvMQj1hJCjKQ==
    ATCODER_PASSWORD:
      secure: zndOc4jqvw5aigjpDnoUSEycIHdwddCYtI8gh/o2yBvDnL3GIT0ea0YavFmdMDMA
  matrix:
    - RUSTUP_HOST: x86_64-pc-windows-msvc
    - RUSTUP_HOST: x86_64-pc-windows-gnu
    - RUSTUP_HOST: i686-pc-windows-msvc
    - RUSTUP_HOST: i686-pc-windows-gnu
install:
  - ps: |
      If ($Env:RUSTUP_HOST -eq 'x86_64-pc-windows-gnu') {
        Set-Item Env:Path "C:\msys64\mingw64\bin;$Env:Path"
        C:\msys64\usr\bin\sh -c "gcc -v 2>&1"
      } ElseIf ($Env:RUSTUP_HOST -eq 'i686-pc-windows-gnu') {
        Set-Item Env:Path "C:\msys64\mingw32\bin;$Env:Path"
        C:\msys64\usr\bin\sh -c "gcc -v 2>&1"
      }
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/${env:RUSTUP_HOST}/rustup-init.exe"
  - rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN% --default-host %RUSTUP_HOST% --no-modify-path
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  - rustc -vV
  - cargo -vV
build_script:
  - cargo +%RUSTUP_TOOLCHAIN% build --release
  - ps: Move-Item "target\release\${env:TARGET}" .\
  - cd C:\projects
  - 7z a %APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%RUSTUP_HOST%.zip
    %APPVEYOR_PROJECT_NAME% -x!%APPVEYOR_PROJECT_NAME%\Cargo.lock -x!%APPVEYOR_PROJECT_NAME%\target -x!%APPVEYOR_PROJECT_NAME%\.git
  - cd %APPVEYOR_BUILD_FOLDER%
test_script:
  - set PATH=C:\Python36-x64;%PATH%
  - python -V
  - ps: |
      If (Test-Path env:ATCODER_USERNAME) {
        C:\msys64\usr\bin\sh -c "cargo test --all 2>&1"
        C:\msys64\usr\bin\sh -c "cargo test --all -- --ignored 2>&1"
        C:\msys64\usr\bin\sh -c "cargo test --all --release 2>&1"
        C:\msys64\usr\bin\sh -c "cargo test --all --release -- --ignored 2>&1"
      } else {
        C:\msys64\usr\bin\sh -c "cargo test --lib 2>&1"
        C:\msys64\usr\bin\sh -c "cargo test --lib -- --ignored 2>&1"
        C:\msys64\usr\bin\sh -c "cargo test --lib --release 2>&1"
        C:\msys64\usr\bin\sh -c "cargo test --lib --release -- --ignored 2>&1"
      }
artifacts:
  - path: '*.zip'
notifications:
  - provider: Email
for:
  - branches:
      only:
        - /^v\d+\.\d+\.\d+.*$/
        - master
    deploy:
      - provider: GitHub
        auth_token:
          secure: khL++opdJh5x79PMMTkOJXPXi8D+ijp0os5Bi02rA4DSApOmuF1VuZWpIzyDZ8pi
        on:
          appveyor_repo_tag: true
