image: Visual Studio 2015

platform: x86_64

environment:
  global:
    TARGET: snowchains.exe
    RUSTUP_TOOLCHAIN: stable
    RUSTUP_HOST: x86_64-pc-windows-msvc
    RUST_BACKTRACE: full
    ATCODER_USERNAME:
      secure: koc3zc/wQPQvMQj1hJCjKQ==
    ATCODER_PASSWORD:
      secure: zndOc4jqvw5aigjpDnoUSEycIHdwddCYtI8gh/o2yBvDnL3GIT0ea0YavFmdMDMA

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/${env:RUSTUP_HOST}/rustup-init.exe"
  - rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN% --default-host %RUSTUP_HOST% --no-modify-path
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  - rustc -vV
  - cargo -vV

build_script:
  - cargo build --release
  - ps: Move-Item "target\release\${env:TARGET}" .\

test_script:
  - set PATH=C:\Python36-x64;%PATH%
  - python -V
  - C:\msys64\usr\bin\sh -c "[ -z \"${SECRET}\" ] && TEST_TARGET=lib || TEST_TARGET=all; cargo test --$TEST_TARGET --release"
  - C:\msys64\usr\bin\sh -c "[ -z \"${SECRET}\" ] && TEST_TARGET=lib || TEST_TARGET=all; cargo test --$TEST_TARGET --release -- --ignored"

before_deploy:
  - cd C:\projects
  - ps: |
      $ZIP = "${env:APPVEYOR_BUILD_FOLDER}/${env:APPVEYOR_PROJECT_NAME}-${env:APPVEYOR_REPO_TAG_NAME}-${env:RUSTUP_HOST}.zip"
      7z a "$ZIP" "${env:APPVEYOR_PROJECT_NAME}/${env:TARGET}" "${env:APPVEYOR_PROJECT_NAME}/LICENSE" "${env:APPVEYOR_PROJECT_NAME}/README.md"
      7z l "$ZIP"
      Push-AppveyorArtifact "$ZIP"
  - cd %APPVEYOR_BUILD_FOLDER%

deploy:
  - provider: GitHub
    artifact: /^.*\.zip$/
    auth_token:
      secure: khL++opdJh5x79PMMTkOJXPXi8D+ijp0os5Bi02rA4DSApOmuF1VuZWpIzyDZ8pi
    on:
      appveyor_repo_tag: true

artifacts:
  - path: '*.exe'

cache:
  - '%HOME%\.cargo\git'
  - '%HOME%\.cargo\registry\index'
  - '%HOME%\.cargo\registry\src'

notifications:
  - provider: Email
    on_build_success: true
    on_build_failure: true

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
