clone_depth: 1
environment:
  global:
    CRATE: snowchains
  matrix:
    - HOST: x86_64-pc-windows-msvc
      TOOLCHAIN: stable
    - HOST: x86_64-pc-windows-gnu
      TOOLCHAIN: stable
    - HOST: i686-pc-windows-msvc
      TOOLCHAIN: stable
    - HOST: i686-pc-windows-gnu
      TOOLCHAIN: stable
    - HOST: x86_64-pc-windows-msvc
      TOOLCHAIN: beta
    - HOST: x86_64-pc-windows-gnu
      TOOLCHAIN: beta
    - HOST: i686-pc-windows-msvc
      TOOLCHAIN: beta
    - HOST: i686-pc-windows-gnu
      TOOLCHAIN: beta
    - HOST: x86_64-pc-windows-msvc
      TOOLCHAIN: nightly
    - HOST: x86_64-pc-windows-gnu
      TOOLCHAIN: nightly
    - HOST: i686-pc-windows-msvc
      TOOLCHAIN: nightly
    - HOST: i686-pc-windows-gnu
      TOOLCHAIN: nightly
matrix:
  allow_failures:
    - HOST: i686-pc-windows-msvc # https://github.com/tokio-rs/tokio-timer/issues/43
    - HOST: i686-pc-windows-gnu
    - TOOLCHAIN: nightly
install:
  - ps: >-
      If ($Env:HOST -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:HOST -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/${env:HOST}/rustup-init.exe"
  - rustup-init.exe -y --default-toolchain %TOOLCHAIN% --default-host %HOST% --no-modify-path
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV
test_script:
  - ps: $Env:PATH += ';C:\Python36-x64'
  - cargo +%TOOLCHAIN% test -v
  - cargo +%TOOLCHAIN% test -v -- --ignored
build: false
before_deploy:
  - cargo +%TOOLCHAIN% build --release
  - ps: >-
      Copy-Item "target\${env:HOST}\release\${env:CRATE}.exe" .\;
      $PROJECT = "C:\projects\${env:APPVEYOR_PROJECT_NAME}";
      $ZIP = "$PROJECT\${env:CRATE}-${env:APPVEYOR_REPO_TAG_NAME}-${env:HOST}.zip";
      Set-Location C:\projects;
      7z a "$ZIP" "${env:APPVEYOR_PROJECT_NAME}\${env:CRATE}.exe" "${env:APPVEYOR_PROJECT_NAME}\README.md" "${env:APPVEYOR_PROJECT_NAME}\LICENSE";
      Set-Location "$PROJECT";
      Push-AppveyorArtifact "$ZIP"
deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    auth_token:
      secure: khL++opdJh5x79PMMTkOJXPXi8D+ijp0os5Bi02rA4DSApOmuF1VuZWpIzyDZ8pi
    on:
      appveyor_repo_tag: true
      TOOLCHAIN: stable
cache:
  - C:\Users\appveyor\.cargo\registry
branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master
notifications:
  - provider: Email
    on_build_success: false
