[package]
name = "snowchains"
version = "0.23.0"
description = "Tools for online programming contests"
license = "MIT"
authors = ["Ryo Yamashita <wariuni@gmail.com>"]
readme = "README.md"
repository = "https://github.com/wariuni/snowchains"

[dependencies]
snowchains_proc_macros = { path = "./proc_macros" }
atty = "0.2.11"
bincode = "1.0.1"
chrono = "0.4.6"
combine = "3.6.3"
cookie = "0.11.0"
ctrlc = "3.1.1"
derive-new = "0.5.6"
derive_more = { git = "https://github.com/JelteF/derive_more", rev = "aebc92485afbe163a7b4e512f4bdc8f183dd07ce" }
diff = "0.1.11"
dirs = "1.0.4"
env_logger = "0.6.0"
failure = "0.1.3"
fs2 = "0.4.3"
futures = "0.1.25"
heck = "0.3.0"
itertools = "0.7.11"
log = "0.4.6"
maplit = "1.0.1"
mime = "0.3.12"
multipart = "0.15.4"
once_cell = "0.1.6"
pbr = "1.0.1"
regex = "1.1.0"
reqwest = "0.9.5"
robots_txt = "0.5.5"
rpassword = "2.1.0"
rprompt = "1.0.3"
select = "0.4.2"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
serde_urlencoded = "0.5.4"
serde_yaml = "0.8.7"
structopt = { version = "0.2.13", features = ["wrap_help"] }
strum = "0.11.0"
strum_macros = "0.11.0"
term_size = "0.3.1"
tokio = "0.1.13"
tokio-process = "0.2.3"
tokio-signal = "0.2.7"
toml = "0.4.9"
unicode-width = "0.1.5"
url = "1.7.2"
webbrowser = "0.3.1"
yaml-rust = "0.4.2"
zip = "0.5.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.6"
winapi-util = "0.1.1"

[dev-dependencies]
if_chain = "0.1.3"
nickel = "0.10.2"
tempdir = "0.3.7"
