[package]
name = "snowchains"
version = "0.23.0"
description = "Tools for online programming contests"
license = "MIT"
authors = ["Ryo Yamashita <wariuni@gmail.com>"]
readme = "README.md"
repository = "https://github.com/wariuni/snowchains"

[dependencies]
ansi_term = "0.11.0"
atty = "0.2.11"
bincode = "1.0.1"
chrono = "0.4.6"
combine = "3.5.1"
cookie = "0.11.0"
diff = "0.1.11"
dirs = "1.0.3"
env_logger = "0.5.13"
failure = "0.1.2"
fs2 = "0.4.3"
futures = "0.1.24"
heck = "0.3.0"
itertools = "0.7.8"
lazy_static = "1.1.0"
log = "0.4.5"
maplit = "1.0.1"
pbr = "1.0.1"
regex = "1.0.5"
reqwest = { version = "0.8.8", features = ["unstable"] }
robots_txt = "0.5.5"
rpassword = "2.0.0"
rprompt = "1.0.3"
select = "0.4.2"
serde = "1.0.78"
serde_derive = "1.0.78"
serde_json = "1.0.27"
serde_urlencoded = "0.5.3"
serde_yaml = "0.8.3"
structopt = "0.2.10"
term = "0.5.1"
tokio = "0.1.8"
tokio-core = "0.1.17"
tokio-process = "0.2.2"
toml = "0.4.6"
unicode-width = "0.1.5"
url = "1.7.1"
webbrowser = "0.3.1"
yaml-rust = "0.4.0"
zip = "0.4.2"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
libc = "0.2.43"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.5"

[dev-dependencies]
nickel = "0.10.1"
tempdir = "0.3.7"
