[package]
authors = ["wariuni <wariuni@gmail.com>"]
description = "Tools for online programming contests"
license = "MIT"
name = "snowchains"
version = "0.15.2"

[dependencies]
httpsession = { git = "https://github.com/wariuni/httpsession", tag = "0.2.1" }
webbrowser = { git = "https://github.com/wariuni/webbrowser-rs", tag = "fix-on-windows" }
bincode = "1.0.0"
chrono = "0.4.0"
cookie = "0.10.1"
custom_derive = "0.1.7"
env_logger = "0.5.4"
error-chain = "0.11.0"
lazy_static = "1.0.0"
log = "0.4.1"
newtype_derive = "0.1.6"
pbr = "1.0.0"
regex = "0.2.7"
reqwest = "0.8.5"
robots_txt = "0.5.3"
rpassword = "2.0.0"
rprompt = "1.0.3"
select = "0.4.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.10"
serde_urlencoded = "0.5.1"
serde_yaml = "0.7.3"
structopt = "0.2.5"
term = "0.5.1"
toml = "0.4.5"
zip = { version = "0.3.1", default_features = false }
