[package]
name = "snowchains"
version = "0.23.0"
description = "Tools for online programming contests"
license = "MIT"
authors = ["Ryo Yamashita <wariuni@gmail.com>"]
readme = "README.md"
repository = "https://github.com/wariuni/snowchains"
edition = "2018"

[dependencies]
snowchains_proc_macros = { path = "./proc_macros" }
atty = "0.2.11"
bincode = "1.0.1"
chrono = "0.4.6"
combine = "3.6.6"
cookie = "0.11.0"
ctrlc = "3.1.1"
derive-new = "0.5.6"
derive_more = "0.14.0"
diff = "0.1.11"
dirs = "1.0.4"
env_logger = "0.6.0"
failure = "0.1.5"
fs2 = "0.4.3"
futures = "0.1.25"
heck = "0.3.1"
if_chain = "0.1.3"
itertools = "0.8.0"
log = "0.4.6"
maplit = "1.0.1"
mime = "0.3.13"
num-traits = "0.2.6"
num_cpus = "1.9.0"
once_cell = "0.1.7"
rayon = "1.0.3"
regex = "1.1.0"
reqwest = { version = "0.9.9", default_features = false, features = ["rustls-tls"] }
robots_txt = "0.6.0"
rpassword = "2.1.0"
rprompt = "1.0.3"
select = "0.4.2"
serde = "1.0.87"
serde_derive = "1.0.87"
serde_json = "1.0.38"
serde_urlencoded = "0.5.4"
serde_yaml = "0.8.8"
structopt = { version = "0.2.14", features = ["wrap_help"] }
strum = "0.13.0"
strum_macros = "0.13.0"
tokio = "0.1.15"
tokio-process = "0.2.3"
toml = "0.4.10"
toml_edit = "0.1.3"
unicode-width = "0.1.5"
url = "1.7.2"
webbrowser = "0.4.0"
yaml-rust = "0.4.2"
zip = "0.5.0"

[target.'cfg(not(windows))'.dependencies]
term_size = "0.3.1"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.6"
winapi-util = "0.1.2"

[dev-dependencies]
md5 = "0.6.1"
tempdir = "0.3.7"
warp = "0.1.12"
