[package]
name = "snowchains"
version = "0.22.0"
description = "Tools for online programming contests"
license = "MIT"
authors = ["wariuni <wariuni@gmail.com>"]
readme = "README.md"
repository = "https://github.com/wariuni/snowchains"

[dependencies]
ansi_term = "~0.11.0"
bincode = "~1.0.1"
chrono = "~0.4.4"
combine = "~3.3.2"
cookie = "~0.10.1"
custom_derive = "~0.1.7"
env_logger = "~0.5.10"
failure = "~0.1.1"
fs2 = "~0.4.3"
futures = "~0.1.21"
heck = "~0.3.0"
itertools = "~0.7.8"
lazy_static = "~1.0.1"
log = "~0.4.2"
maplit = "~1.0.1"
newtype_derive = "~0.1.6"
pbr = "~1.0.1"
regex = "~1.0.1"
reqwest = { version = "~0.8.6", features = ["unstable"] }
robots_txt = "~0.5.5"
rpassword = "~2.0.0"
rprompt = "~1.0.3"
select = "~0.4.2"
serde = "~1.0.67"
serde_derive = "~1.0.67"
serde_json = "~1.0.22"
serde_urlencoded = "~0.5.2"
serde_yaml = "~0.7.5"
structopt = "~0.2.10"
term = "~0.5.1"
tokio-core = "~0.1.17"
toml = "~0.4.6"
unicode-width = "~0.1.5"
url = "~1.7.0"
webbrowser = { git = "https://github.com/amodm/webbrowser-rs", rev = "a2620121c945f78874e9ab1c52677b2934f48121" }
yaml-rust = "~0.4.0"
zip = "~0.4.2"

[dev-dependencies]
nickel = "~0.10.1"
tempdir = "~0.3.7"
