[package]
name = "snowchains"
version = "0.19.1"
description = "Tools for online programming contests"
license = "MIT"
authors = ["wariuni <wariuni@gmail.com>"]
readme = "README.md"
repository = "https://github.com/wariuni/snowchains"

[dependencies]
httpsession = { git = "https://github.com/wariuni/httpsession", tag = "0.2.2" }
bincode = "1.0.0"
chrono = "0.4.0"
cookie = "0.10.1"
custom_derive = "0.1.7"
env_logger = "0.5.6"
error-chain = "0.11.0"
futures = "0.1.18"
futures-timer = "0.1.1"
lazy_static = "1.0.0"
log = "0.4.1"
newtype_derive = "0.1.6"
pbr = "1.0.0"
regex = "0.2.10"
robots_txt = "0.5.3"
rpassword = "2.0.0"
rprompt = "1.0.3"
select = "0.4.2"
serde = "1.0.33"
serde_derive = "1.0.33"
serde_json = "1.0.12"
serde_urlencoded = "0.5.1"
serde_yaml = "0.7.3"
structopt = "0.2.5"
term = "0.5.1"
toml = "0.4.5"
webbrowser = { git = "https://github.com/amodm/webbrowser-rs", rev = "a2620121c945f78874e9ab1c52677b2934f48121" }
zip = { version = "0.3.1", default_features = false }

[dev-dependencies]
nickel = "0.10.1"
