[package]
authors = ["wariuni <wariuni@gmail.com>"]
description = "Tools for online programming contests"
license = "MIT"
name = "snowchains"
version = "0.6.15"
[dependencies]
clap = "2.26.0"
cookie = "0.9.1"
error-chain = "0.10.0"
regex = "0.2.2"
reqwest = "0.7.2"
rpassword = "1.0.2"
rprompt = "1.0.3"
select = "0.4.2"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
serde_urlencoded = "0.5.1"
serde_yaml = "0.7.1"
term = "0.4.6"
toml = "0.4.5"
