[package]
authors = ["wariuni <wariuni@gmail.com>"]
description = "Tools for online programming contests"
license = "MIT"
name = "snowchains"
version = "0.5.0"

[dependencies]
clap = "2.25.0"
cookie = "0.9.1"
html5ever = "0.18.0"
regex = "0.2.2"
reqwest = "0.6.2"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
serde_urlencoded = "0.5.1"
term = "0.4.6"
toml = "0.4.2"
