[package]
authors = ["wariuni <wariuni@gmail.com>"]
description = "Tools for online programming contests"
license = "MIT"
name = "snowchains"
version = "0.11.15"
[dependencies]
bincode = "0.9.2"
chrono = "0.4.0"
clap = "2.26.2"
cookie = "0.10.1"
custom_derive = "0.1.7"
env_logger = "0.4.3"
error-chain = "0.11.0"
lazy_static = "0.2.9"
log = "0.3.8"
newtype_derive = "0.1.6"
pbr = "1.0.0"
regex = "0.2.2"
reqwest = "0.8.0"
rpassword = "1.0.2"
rprompt = "1.0.3"
select = "0.4.2"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
serde_urlencoded = "0.5.1"
serde_yaml = "0.7.1"
term = "0.4.6"
toml = "0.4.5"

[dependencies.webbrowser]
git = "https://github.com/wariuni/webbrowser-rs"
rev = "c16240a8495fc0e75d0e0aaa53dbdd87edf1565d"

[dependencies.zip]
default-features = false
version = "0.2.6"
