[package]
name = "snowchains"
version = "0.21.0"
description = "Tools for online programming contests"
license = "MIT"
authors = ["wariuni <wariuni@gmail.com>"]
readme = "README.md"
repository = "https://github.com/wariuni/snowchains"

[dependencies]
bincode = "1.0.0"
chrono = "0.4.2"
combine = "3.2.0"
cookie = "0.10.1"
custom_derive = "0.1.7"
env_logger = "0.5.10"
error-chain = "0.11.0"
fs2 = "0.4.3"
futures = "0.2.1"
heck = "0.3.0"
itertools = "0.7.8"
lazy_static = "1.0.0"
log = "0.4.1"
maplit = "1.0.1"
newtype_derive = "0.1.6"
pbr = "1.0.1"
regex = "1.0.0"
reqwest = "0.8.5"
robots_txt = "0.5.4"
rpassword = "2.0.0"
rprompt = "1.0.3"
select = "0.4.2"
serde = "1.0.50"
serde_derive = "1.0.50"
serde_json = "1.0.17"
serde_urlencoded = "0.5.1"
serde_yaml = "0.7.4"
structopt = "0.2.8"
term = "0.5.1"
toml = "0.4.6"
unicode-width = "0.1.4"
url = "1.7.0"
webbrowser = { git = "https://github.com/amodm/webbrowser-rs", rev = "a2620121c945f78874e9ab1c52677b2934f48121" }
zip = "0.3.2"

[dev-dependencies]
futures-timer = { git = "https://github.com/alexcrichton/futures-timer", rev = "1d438ec7b5dd41f8727dac1974c0f4cf1c397f5a" }
nickel = "0.10.1"
tempdir = "0.3.7"
