[package]
authors = ["wariuni <wariuni@gmail.com>"]
description = "Tools for online programming contests"
license = "MIT"
name = "snowchains"
version = "0.3.2"

[dependencies]
clap = "2.25.0"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
term = "0.4.6"
toml = "0.4.2"
