[config]
skip_core_tasks = true

[tasks.clean]
category = "Cleanup"
command = "cargo"
args = ["clean"]
dependencies = ["clean-subcrates"]
workspace = false

[tasks.clean-subcrates]
category = "Cleanup"
cwd = "./proc_macros"
command = "cargo"
args = ["clean"]
workspace = false

[tasks.check-format]
category = "Test"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
toolchain = "stable"
workspace = false

[tasks.clippy]
category = "Test"
command = "cargo"
args = ["clippy", "--all", "--all-targets", "--", "-D", "warnings"]
toolchain = "stable"
dependencies = ["touch"]
workspace = false

[tasks.test]
category = "Test"
script = [
'''
if which envchain > /dev/null; then
  envchain snowchains cargo test --all
elif which dotenv > /dev/null && [ -f ./.env ]; then
  dotenv cargo test --all
else
  cargo test --all
fi
''',
]
script_runner = "bash"
script_extension = "bash"
workspace = false

[tasks.format]
category = "Development"
command = "cargo"
args = ["fmt", "--all"]
toolchain = "stable"
workspace = false

[tasks.upgrade-dependencies]
category = "Development"
dependencies = ["upgrade", "update"]
workspace = false

[tasks.upgrade]
category = "Development"
command = "cargo"
args = ["upgrade", "--all"]
workspace = false

[tasks.update]
category = "Development"
command = "cargo"
args = ["update"]
dependencies = ["update-subcrates"]
workspace = false

[tasks.update-subcrates]
category = "Development"
cwd = "./proc_macros"
command = "cargo"
args = ["update"]
workspace = false

[tasks.touch]
category = "Development"
script = ["find ./src ./tests ./proc_macros/src -type f | xargs touch"]
script_runner = "bash"
script_extension = "bash"
workspace = false

[tasks.default]
category = "Disabled"
disabled = true
workspace = false

[tasks.empty]
category = "Disabled"
disabled = true
workspace = false
