[package]
name = "snowchains_proc_macros"
version = "0.1.0"
license = "MIT"
authors = ["Ryo Yamashita <wariuni@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
combine = "3.6.3"
if_chain = "0.1.3"
proc-macro2 = "0.4.24"
quote = "0.6.10"
syn = { version = "0.15.22", features = ["full"] }
